In [1]:
# Importamos librerías para el tratamiento de datos
import pandas as pd
import numpy as np
# Config pandas para ver todas las columnas 
pd.set_option("display.max_columns", None)


import mysql.connector

In [2]:

# ABRIMOS CSV

df = pd.read_csv('data/HR RAW DATA_CLEAN.csv', index_col = 0)

print(df.shape)

df.head(2)

(1486, 27)

,EmployeeNumber,Age,Gender,Education,EducationField,NumCompaniesWorked,JobLevel,JobRole,Department,JobInvolvement,PerformanceRating,Attrition,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,MonthlyIncome,StockOptionLevel,PercentSalaryHike,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,TrainingTimesLastYear,BusinessTravel,DistanceFromHome,OverTime,RemoteWork
0,162.0,51,Male,3,NaN,7,5,Research Director,Unknown,3,3.0,No,3,1.0,3,3.0,19537.0,0,13,20,15,15,5,Non-Travel,6,No,Yes
1,259.0,52,Male,4,Life Sciences,0,5,Manager,Unknown,2,3.0,No,3,3.0,1,3.0,19999.0,1,14,33,11,9,5,Non-Travel,1,No,Yes

In [3]:

# CREACION SCHEMA

# Nos conectamos a nuestro servidor local de SQL para poder hacer la creacion del Schema, las tablas y la inserción de datos

cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1")
    
mycursor = cnx.cursor()

query_creacion_bbdd = "CREATE SCHEMA IF NOT EXISTS `Proyecto` DEFAULT CHARACTER SET utf8mb4;"
try:
    mycursor.execute(query_creacion_bbdd)
    print(mycursor)
    cnx.close()
# Si hubiera algun error, ejemplo contraseña incorrecta, indicamos que en lugar de saltar una excepcion se imprima el mensaje con el error en particular
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")
    cnx.close()

MySQLCursor: CREATE SCHEMA IF NOT EXISTS `Proyecto` D..

In [4]:
# CREACION TABLA WORK


cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()

query_creacion_tabla_work = """
                            CREATE TABLE IF NOT EXISTS `work` (
                            `idWork` INT NOT NULL AUTO_INCREMENT,
                            `JobLevel` INT UNSIGNED NOT NULL,
                            `JobRole` VARCHAR(45) NOT NULL,
                            `Department` VARCHAR(45) NULL,
                            PRIMARY KEY (`idWork`))
                            ENGINE = InnoDB;
                            """
try:
    mycursor.execute(query_creacion_tabla_work)
    print(mycursor)
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

MySQLCursor:
                            CREATE TABL..

In [5]:

# CREACION TABLA SATISFACTION SURVEYS

cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()

query_creacion_tabla_satisfaction_surveys = """
                                    CREATE TABLE IF NOT EXISTS `satisfaction_surveys` (
                                    `idSatisfaction` INT NOT NULL AUTO_INCREMENT,
                                    `JobInvolvement` INT UNSIGNED NULL,
                                    `PerformanceRating` INT UNSIGNED NULL,
                                    `EnvironmentSatisfaction` INT UNSIGNED NULL,
                                    `RelationshipSatisfaction` INT UNSIGNED NULL,
                                    `WorkLifeBalance` INT UNSIGNED NULL,
                                    `JobSatisfaction` INT UNSIGNED NULL,
                                    PRIMARY KEY (`idSatisfaction`))
                                    ENGINE = InnoDB;"""
try:
    mycursor.execute(query_creacion_tabla_satisfaction_surveys)
    print(mycursor)
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

MySQLCursor:
                                    CRE..

In [6]:

# CREACION TABLA EMPLOYEES

cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()

query_creacion_tabla_employees = """
                            CREATE TABLE IF NOT EXISTS `employees` (
                            `idemployee` INT NOT NULL AUTO_INCREMENT,
                            `EmployeeNumber` VARCHAR(45) NULL,
                            `Age` INT UNSIGNED NULL,
                            `Gender` VARCHAR(45) NULL,
                            `Education` INT UNSIGNED NULL,
                            `EducationField` VARCHAR(45) NULL,
                            `NumCompaniesWorked` INT UNSIGNED NULL,
                            `MonthlyIncome` INT UNSIGNED NULL,
                            `StockOptionLevel` INT NULL,
                            `YearsAtCompany` INT UNSIGNED NULL,
                            `YearsSinceLastPromotion` INT UNSIGNED NULL,
                            `YearsWithCurrManager` INT UNSIGNED NULL,
                            `TrainingTimesLastYear` INT UNSIGNED NULL,
                            `DistanceFromHome` INT UNSIGNED NULL,
                            `Attrition` VARCHAR(45) NOT NULL,
                            `idwork` INT NOT NULL,
                            `idSatisfaction` INT NOT NULL,
                            PRIMARY KEY (`idemployee`),
                            INDEX `fk_employees_work_idx` (`idwork` ASC) VISIBLE,
                            INDEX `fk_employees_Satisfaction_Surveys1_idx` (`idSatisfaction` ASC) VISIBLE,
                            CONSTRAINT `fk_employees_work`
                                FOREIGN KEY (`idwork`)
                                REFERENCES `proyecto`.`work` (`idwork`)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE,
                            CONSTRAINT `fk_employees_Satisfaction_Surveys1`
                                FOREIGN KEY (`idSatisfaction`)
                                REFERENCES `proyecto`.`Satisfaction_Surveys` (`idSatisfaction`)
                                ON DELETE CASCADE
                                ON UPDATE CASCADE)
                            ENGINE = InnoDB;
                            """
try:
    mycursor.execute(query_creacion_tabla_employees)
    print(mycursor)
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

MySQLCursor:
                            CREATE TABL..

In [7]:

# CREACION TABLA WORK_INFO

cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()

query_creacion_tabla_work_info =  """
                                CREATE TABLE IF NOT EXISTS `work_info` (
                                `idwork_info` INT NOT NULL AUTO_INCREMENT,
                                `RemoteWork` VARCHAR(45) NOT NULL,
                                `OverTime` VARCHAR(45) NULL,
                                `BusinessTravel` VARCHAR(45) NULL,
                                `idwork` INT NOT NULL,
                                PRIMARY KEY (`idwork_info`),
                                INDEX `fk_work_info_work1_idx` (`idwork` ASC) VISIBLE,
                                CONSTRAINT `fk_work_info_work1`
                                    FOREIGN KEY (`idwork`)
                                    REFERENCES `proyecto`.`work` (`idwork`)
                                    ON DELETE CASCADE
                                    ON UPDATE CASCADE)
                                ENGINE = InnoDB;
                                    """
try:
    mycursor.execute(query_creacion_tabla_work_info)
    print(mycursor)
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

MySQLCursor:
                                CREATE ..

In [8]:
# INSERCION DATOS PRIMERO EN LAS TABLAS CUYA PRIMARY KEY ES FOREIGN KEY DE OTRA TABLA 

# INSERCION DATOS EN WORK, PARA LO CUAL PRIMERO EXTRAEMOS DEL DATAFRAME UNA LISTA QUE CONTIENE LA INFORMACION
# FILA A FILA EN TUPLAS, CADA TUPLA ES UNA FILA. 

valores_tabla_work = list(set(zip([int(x) for x in df['JobLevel'].values],df['JobRole'].values, df['Department'].values)))

print(valores_tabla_work)

[(4, 'Manufacturing Director', 'Unknown'), (4, 'Healthcare Representative', 'Research & Development'), (3, 'Laboratory Technician', 'Unknown'), (2, 'Human Resources', 'Human Resources'), (2, 'Manufacturing Director', 'Research & Development'), (1, 'Laboratory Technician', 'Research & Development'), (3, 'Manufacturing Director', 'Unknown'), (3, 'Healthcare Representative', 'Research & Development'), (1, 'Human Resources', 'Human Resources'), (1, 'Sales Representative', 'Unknown'), (2, 'Laboratory Technician', 'Research & Development'), (1, 'Sales Representative', 'Sales'), (4, 'Sales Executive', 'Sales'), (2, 'Sales Representative', 'Sales'), (4, 'Sales Executive', 'Unknown'), (2, 'Sales Representative', 'Unknown'), (3, 'Sales Executive', 'Sales'), (3, 'Sales Executive', 'Unknown'), (2, 'Human Resources', 'Unknown'), (2, 'Manufacturing Director', 'Unknown'), (2, 'Healthcare Representative', 'Research & Development'), (1, 'Human Resources', 'Unknown'), (4, 'Healthcare Representative', 'Unknown'), (3, 'Healthcare Representative', 'Unknown'), (1, 'Laboratory Technician', 'Unknown'), (4, 'Manager', 'Research & Development'), (3, 'Manager', 'Research & Development'), (2, 'Laboratory Technician', 'Unknown'), (2, 'Research Scientist', 'Research & Development'), (4, 'Manager', 'Human Resources'), (1, 'Research Scientist', 'Research & Development'), (3, 'Research Scientist', 'Unknown'), (4, 'Research Director', 'Research & Development'), (5, 'Manager', 'Research & Development'), (3, 'Human Resources', 'Human Resources'), (5, 'Research Director', 'Research & Development'), (2, 'Sales Executive', 'Sales'), (2, 'Healthcare Representative', 'Unknown'), (2, 'Sales Executive', 'Unknown'), (3, 'Research Director', 'Research & Development'), (4, 'Manager', 'Unknown'), (4, 'Manager', 'Sales'), (2, 'Research Scientist', 'Unknown'), (4, 'Manufacturing Director', 'Research & Development'), (3, 'Manufacturing Director', 'Research & Development'), (3, 'Manager', 'Sales'), (3, 'Manager', 'Unknown'), (1, 'Research Scientist', 'Unknown'), (3, 'Human Resources', 'Unknown'), (4, 'Research Director', 'Unknown'), (5, 'Manager', 'Sales'), (5, 'Manager', 'Unknown'), (5, 'Research Director', 'Unknown'), (3, 'Research Director', 'Unknown')]

In [9]:
# UNA VEZ TENEMOS LOS VALORES LOS INSERTAMOS EN LA TABLA WORK


cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()
query_insercion_work = "INSERT INTO work (JobLevel, JobRole, Department) VALUES (%s, %s, %s)"

try:
    mycursor.executemany(query_insercion_work,valores_tabla_work)
    cnx.commit()
    print(mycursor.rowcount, "registros insertados")
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

54 registros insertados

In [10]:
# HACEMOS EL MISMO PROCESO PARA LA TABLA SATISFACTION SURVEYS, PRIMERO EXTRAEMOS LOS DATOS EN LISTA DE TUPLAS. 
# USAMOS SET EN AMBOS CASOS PARA QUE NO HAYA CONJUNTO DE DATOS DUPLICADOS. 

valores_tabla_satisfaction = list(set(zip(
    [int(x) for x in df['JobInvolvement'].values],
    [float(x) for x in df['PerformanceRating'].values],
    [int(x) for x in df['EnvironmentSatisfaction'].values],
    [int(x) for x in df['RelationshipSatisfaction'].values],
    [float(x) for x in df['WorkLifeBalance'].values],
    [int(x) for x in df['JobSatisfaction'].values])))
    
print(valores_tabla_satisfaction)

[(2, 3.0, 2, 3, 2.0, 3), (3, 3.0, 4, 2, 2.0, 1), (4, 3.0, 3, 1, 3.0, 2), (2, 3.0, 1, 4, 3.0, 4), (2, 3.0, 2, 4, 3.0, 1), (1, 3.0, 2, 2, 3.0, 1), (1, 4.0, 3, 1, 3.0, 1), (3, 4.0, 1, 1, 4.0, 1), (3, 3.0, 4, 2, 3.0, 2), (2, 3.0, 3, 4, 4.0, 2), (2, 4.0, 2, 1, 3.0, 3), (3, 3.0, 4, 4, 3.0, 4), (3, 3.0, 3, 1, 4.0, 4), (4, 4.0, 3, 1, 3.0, 1), (4, 3.0, 3, 2, 2.0, 4), (3, 4.0, 2, 3, 3.0, 3), (1, 3.0, 3, 4, 3.0, 3), (2, 3.0, 3, 1, 2.0, 1), (2, 4.0, 1, 4, 3.0, 4), (3, 3.0, 1, 3, 2.0, 4), (4, 4.0, 2, 2, 3.0, 2), (2, 3.0, 1, 1, 3.0, 2), (4, 3.0, 3, 4, 3.0, 3), (2, 3.0, 1, 3, 3.0, 4), (3, 3.0, 1, 4, 3.0, 2), (3, 3.0, 2, 4, 1.0, 1), (3, 4.0, 3, 3, 3.0, 3), (3, 3.0, 3, 3, 3.0, 1), (3, 4.0, 1, 4, 4.0, 2), (2, 3.0, 4, 2, 3.0, 1), (2, 3.0, 4, 1, 2.0, 2), (3, 4.0, 1, 1, 3.0, 4), (3, 4.0, 4, 1, 3.0, 4), (3, 3.0, 4, 1, 4.0, 4), (3, 3.0, 2, 4, 2.0, 2), (1, 3.0, 2, 3, 3.0, 2), (3, 3.0, 4, 3, 2.0, 1), (3, 4.0, 2, 2, 3.0, 3), (2, 4.0, 2, 2, 2.0, 2), (3, 3.0, 2, 1, 1.0, 4), (2, 3.0, 4, 3, 3.0, 4), (3, 4.0, 2, 1, 2.0, 4), (3, 3.0, 3, 3, 4.0, 1), (2, 3.0, 4, 4, 2.0, 4), (3, 4.0, 4, 1, 4.0, 4), (2, 3.0, 2, 2, 4.0, 3), (4, 3.0, 3, 3, 1.0, 2), (3, 3.0, 1, 2, 2.0, 3), (3, 4.0, 4, 3, 2.0, 1), (4, 3.0, 3, 3, 4.0, 4), (1, 4.0, 4, 2, 3.0, 1), (3, 4.0, 1, 3, 2.0, 1), (2, 3.0, 4, 2, 2.0, 4), (1, 4.0, 1, 4, 3.0, 3), (2, 3.0, 3, 3, 1.0, 2), (4, 3.0, 2, 3, 3.0, 1), (1, 3.0, 2, 4, 3.0, 1), (3, 3.0, 3, 4, 1.0, 2), (1, 4.0, 3, 3, 4.0, 3), (3, 3.0, 4, 4, 2.0, 3), (3, 3.0, 1, 2, 3.0, 4), (3, 3.0, 3, 1, 3.0, 3), (3, 3.0, 4, 1, 1.0, 3), (4, 4.0, 3, 3, 3.0, 1), (3, 3.0, 3, 2, 4.0, 1), (3, 3.0, 3, 4, 4.0, 3), (4, 3.0, 3, 1, 3.0, 1), (1, 3.0, 2, 1, 3.0, 4), (2, 4.0, 1, 4, 2.0, 3), (2, 4.0, 3, 1, 3.0, 3), (3, 4.0, 2, 3, 2.0, 1), (2, 3.0, 3, 4, 4.0, 1), (2, 3.0, 4, 3, 2.0, 3), (3, 3.0, 4, 4, 3.0, 3), (3, 4.0, 1, 3, 1.0, 4), (3, 3.0, 1, 1, 3.0, 4), (2, 3.0, 4, 1, 1.0, 1), (2, 4.0, 2, 4, 2.0, 4), (4, 4.0, 2, 1, 2.0, 3), (1, 3.0, 3, 4, 3.0, 2), (2, 3.0, 3, 2, 2.0, 3), (2, 3.0, 2, 4, 2.0, 4), (3, 3.0, 1, 3, 2.0, 3), (2, 3.0, 1, 1, 3.0, 1), (4, 3.0, 3, 4, 3.0, 2), (2, 3.0, 1, 3, 3.0, 3), (4, 4.0, 4, 3, 3.0, 2), (3, 3.0, 3, 2, 3.0, 4), (3, 3.0, 1, 4, 3.0, 1), (1, 3.0, 3, 2, 1.0, 4), (3, 4.0, 3, 3, 3.0, 2), (3, 4.0, 1, 4, 4.0, 1), (4, 3.0, 4, 4, 3.0, 4), (2, 3.0, 1, 4, 2.0, 3), (3, 4.0, 4, 1, 3.0, 3), (2, 3.0, 3, 4, 3.0, 4), (3, 3.0, 2, 3, 3.0, 3), (3, 3.0, 4, 2, 2.0, 4), (3, 3.0, 2, 1, 3.0, 4), (2, 3.0, 4, 4, 1.0, 2), (2, 4.0, 2, 3, 2.0, 4), (3, 3.0, 4, 3, 1.0, 4), (2, 4.0, 1, 3, 3.0, 3), (3, 3.0, 2, 3, 4.0, 4), (1, 4.0, 3, 3, 3.0, 1), (2, 3.0, 2, 2, 4.0, 2), (4, 3.0, 4, 2, 3.0, 1), (3, 3.0, 1, 4, 2.0, 4), (3, 4.0, 1, 4, 3.0, 4), (4, 3.0, 2, 4, 4.0, 4), (3, 3.0, 4, 4, 2.0, 2), (3, 3.0, 4, 1, 3.0, 3), (3, 3.0, 3, 1, 3.0, 2), (3, 3.0, 3, 3, 3.0, 4), (2, 3.0, 1, 2, 4.0, 3), (3, 4.0, 4, 4, 1.0, 1), (3, 3.0, 3, 4, 4.0, 2), (2, 3.0, 2, 3, 4.0, 1), (4, 3.0, 3, 1, 2.0, 4), (4, 3.0, 1, 1, 3.0, 1), (3, 3.0, 1, 1, 2.0, 2), (4, 3.0, 1, 3, 3.0, 3), (3, 3.0, 4, 3, 4.0, 4), (2, 3.0, 3, 2, 1.0, 1), (2, 3.0, 2, 4, 1.0, 2), (3, 4.0, 3, 2, 3.0, 4), (3, 3.0, 1, 1, 3.0, 3), (1, 3.0, 4, 4, 4.0, 4), (3, 4.0, 4, 4, 2.0, 1), (2, 3.0, 3, 2, 2.0, 2), (2, 3.0, 2, 2, 3.0, 1), (4, 4.0, 3, 4, 3.0, 2), (2, 4.0, 3, 4, 3.0, 4), (2, 3.0, 2, 1, 3.0, 4), (4, 3.0, 3, 4, 3.0, 1), (3, 3.0, 3, 2, 3.0, 3), (3, 3.0, 1, 3, 4.0, 2), (3, 3.0, 2, 3, 2.0, 1), (4, 3.0, 4, 4, 3.0, 3), (3, 3.0, 3, 1, 2.0, 1), (3, 3.0, 2, 4, 4.0, 1), (3, 3.0, 3, 3, 2.0, 3), (2, 4.0, 1, 3, 2.0, 1), (3, 4.0, 4, 1, 3.0, 2), (2, 3.0, 3, 4, 3.0, 3), (3, 3.0, 2, 3, 3.0, 2), (3, 3.0, 2, 1, 3.0, 3), (1, 4.0, 4, 1, 2.0, 4), (1, 3.0, 2, 3, 2.0, 4), (1, 3.0, 3, 3, 3.0, 1), (2, 4.0, 4, 2, 3.0, 2), (4, 3.0, 3, 3, 3.0, 1), (2, 3.0, 1, 2, 3.0, 2), (4, 3.0, 4, 1, 3.0, 4), (2, 3.0, 4, 4, 4.0, 2), (2, 4.0, 3, 3, 3.0, 3), (3, 3.0, 1, 2, 2.0, 1), (3, 3.0, 1, 4, 2.0, 3), (4, 3.0, 4, 2, 2.0, 4), (2, 3.0, 4, 1, 3.0, 4), (4, 3.0, 1, 2, 2.0, 4), (3, 4.0, 1, 2, 3.0, 4), (3, 4.0, 1, 4, 3.0, 3), (3, 3.0, 2, 2, 3.0, 2), (3, 3.0, 2, 4, 3.0, 4), (4, 3.0, 4, 3, 3.0, 2), (3, 3.0, 4, 1, 3.0, 2), (3, 4.0, 3, 4, 1.0, 4), (2, 3.0, 1, 3, 2.0, 1), (3, 3.0, 4, 2, 1.0, 3), (2, 4.0, 1, 2, 3.0, 2), (3, 3.0, 2, 2, 4.0, 3), (1, 3.0, 1, 2, 3.0, 2), (2, 4.0, 4, 1, 3.0, 1), (4, 3.0, 3, 1, 2.0, 3), (3, 4.0, 2, 4, 2.0, 1), (3, 3.0, 1, 1, 2.0, 1), (4, 3.0, 1, 3, 3.0, 2), (1, 3.0, 1, 4, 3.0, 2), (1, 3.0, 4, 2, 3.0, 1), (2, 3.0, 4, 3, 2.0, 1), (3, 4.0, 3, 2, 3.0, 3), (2, 4.0, 3, 4, 2.0, 2), (3, 4.0, 4, 4, 4.0, 1), (3, 4.0, 2, 4, 3.0, 2), (3, 4.0, 3, 3, 1.0, 4), (3, 3.0, 1, 1, 3.0, 2), (1, 4.0, 3, 3, 3.0, 4), (2, 4.0, 3, 2, 3.0, 1), (2, 3.0, 2, 3, 3.0, 4), (4, 3.0, 2, 4, 3.0, 2), (3, 3.0, 3, 2, 3.0, 2), (2, 3.0, 1, 1, 2.0, 3), (3, 3.0, 1, 3, 4.0, 1), (4, 3.0, 1, 4, 3.0, 1), (1, 3.0, 4, 3, 3.0, 3), (3, 3.0, 4, 2, 4.0, 3), (3, 3.0, 3, 3, 2.0, 2), (1, 3.0, 3, 2, 3.0, 2), (3, 4.0, 4, 4, 1.0, 4), (3, 3.0, 2, 1, 3.0, 2), (2, 3.0, 2, 2, 2.0, 4), (4, 4.0, 1, 2, 3.0, 2), (3, 4.0, 4, 2, 3.0, 3), (4, 3.0, 1, 3, 2.0, 1), (1, 3.0, 3, 3, 2.0, 4), (3, 4.0, 3, 1, 3.0, 2), (2, 4.0, 3, 2, 2.0, 4), (3, 3.0, 1, 4, 4.0, 3), (2, 3.0, 4, 2, 4.0, 2), (3, 4.0, 3, 1, 4.0, 3), (2, 4.0, 3, 3, 3.0, 2), (2, 3.0, 2, 2, 3.0, 4), (4, 4.0, 3, 2, 3.0, 3), (4, 3.0, 4, 2, 2.0, 3), (2, 3.0, 4, 1, 3.0, 3), (4, 3.0, 1, 2, 2.0, 3), (3, 4.0, 1, 2, 3.0, 3), (1, 3.0, 4, 1, 2.0, 4), (4, 3.0, 3, 1, 1.0, 2), (3, 3.0, 2, 2, 3.0, 1), (2, 4.0, 2, 2, 4.0, 4), (3, 3.0, 2, 4, 3.0, 3), (4, 3.0, 2, 2, 3.0, 4), (4, 3.0, 4, 3, 3.0, 1), (3, 3.0, 4, 1, 3.0, 1), (1, 4.0, 2, 2, 3.0, 3), (3, 3.0, 4, 4, 1.0, 4), (3, 3.0, 3, 1, 2.0, 4), (2, 3.0, 3, 4, 2.0, 1), (3, 3.0, 3, 4, 3.0, 4), (3, 4.0, 4, 3, 3.0, 2), (2, 3.0, 4, 4, 3.0, 4), (2, 3.0, 2, 1, 2.0, 1), (3, 3.0, 2, 2, 2.0, 4), (2, 4.0, 4, 4, 3.0, 2), (2, 3.0, 3, 1, 3.0, 2), (2, 3.0, 1, 1, 1.0, 1), (4, 3.0, 3, 4, 2.0, 4), (2, 3.0, 3, 3, 3.0, 4), (3, 3.0, 4, 1, 2.0, 4), (2, 3.0, 1, 3, 1.0, 3), (3, 3.0, 2, 3, 1.0, 4), (3, 3.0, 1, 4, 1.0, 1), (4, 4.0, 1, 4, 4.0, 4), (4, 3.0, 2, 4, 3.0, 1), (2, 3.0, 2, 4, 4.0, 1), (3, 3.0, 1, 3, 3.0, 4), (3, 3.0, 4, 2, 4.0, 2), (3, 3.0, 3, 3, 2.0, 1), (3, 3.0, 1, 1, 1.0, 3), (4, 3.0, 3, 2, 3.0, 4), (3, 4.0, 1, 1, 2.0, 4), (2, 4.0, 1, 3, 1.0, 3), (3, 3.0, 4, 3, 3.0, 2), (2, 3.0, 2, 2, 2.0, 3), (2, 4.0, 2, 2, 3.0, 3), (3, 4.0, 4, 4, 3.0, 3), (3, 4.0, 2, 4, 2.0, 4), (3, 4.0, 4, 2, 3.0, 2), (3, 4.0, 3, 1, 3.0, 1), (3, 3.0, 1, 1, 4.0, 4), (4, 3.0, 4, 2, 1.0, 1), (4, 3.0, 3, 3, 2.0, 3), (2, 3.0, 3, 2, 3.0, 3), (3, 4.0, 3, 3, 4.0, 3), (4, 3.0, 2, 2, 2.0, 2), (1, 3.0, 4, 4, 3.0, 1), (3, 3.0, 3, 2, 2.0, 1), (1, 3.0, 3, 1, 3.0, 1), (2, 3.0, 4, 1, 3.0, 2), (3, 3.0, 3, 4, 2.0, 3), (1, 4.0, 2, 2, 2.0, 1), (4, 3.0, 1, 4, 2.0, 3), (3, 4.0, 3, 4, 3.0, 3), (3, 3.0, 3, 1, 1.0, 2), (3, 3.0, 3, 3, 1.0, 4), (2, 3.0, 1, 4, 3.0, 3), (3, 3.0, 4, 2, 3.0, 1), (2, 3.0, 1, 4, 4.0, 4), (3, 3.0, 3, 1, 4.0, 3), (2, 4.0, 4, 3, 3.0, 1), (3, 4.0, 2, 3, 3.0, 2), (2, 3.0, 4, 4, 3.0, 3), (3, 4.0, 2, 4, 1.0, 3), (4, 3.0, 1, 3, 2.0, 4), (3, 3.0, 4, 4, 4.0, 4), (3, 3.0, 3, 2, 1.0, 4), (4, 3.0, 2, 1, 3.0, 3), (3, 3.0, 2, 2, 2.0, 3), (2, 3.0, 3, 1, 3.0, 1), (2, 3.0, 3, 3, 3.0, 3), (2, 3.0, 3, 4, 1.0, 4), (3, 3.0, 2, 3, 1.0, 3), (1, 3.0, 2, 2, 2.0, 3), (4, 3.0, 3, 4, 4.0, 3), (3, 3.0, 4, 1, 4.0, 3), (2, 3.0, 1, 3, 4.0, 4), (3, 3.0, 2, 4, 2.0, 1), (2, 3.0, 2, 4, 3.0, 4), (3, 3.0, 1, 3, 3.0, 3), (1, 3.0, 2, 2, 3.0, 4), (2, 3.0, 4, 3, 3.0, 3), (3, 4.0, 2, 1, 2.0, 3), (2, 3.0, 2, 2, 2.0, 2), (3, 3.0, 4, 3, 3.0, 1), (4, 4.0, 3, 1, 3.0, 4), (1, 3.0, 1, 1, 1.0, 2), (2, 3.0, 4, 3, 4.0, 4), (3, 4.0, 4, 4, 3.0, 2), (2, 3.0, 3, 1, 2.0, 4), (3, 3.0, 1, 1, 4.0, 3), (3, 3.0, 1, 4, 4.0, 1), (2, 3.0, 3, 2, 3.0, 2), (3, 4.0, 1, 2, 1.0, 4), (3, 3.0, 1, 2, 3.0, 3), (4, 3.0, 2, 4, 2.0, 3), (4, 3.0, 4, 4, 4.0, 4), (2, 3.0, 4, 2, 3.0, 4), (2, 3.0, 3, 3, 2.0, 2), (2, 4.0, 1, 1, 3.0, 1), (3, 3.0, 3, 4, 2.0, 2), (1, 3.0, 4, 3, 2.0, 4), (3, 4.0, 3, 4, 3.0, 2), (3, 3.0, 4, 1, 1.0, 2), (1, 3.0, 2, 1, 3.0, 3), (2, 3.0, 1, 4, 3.0, 2), (3, 3.0, 4, 3, 2.0, 4), (2, 3.0, 3, 3, 2.0, 4), (3, 3.0, 4, 4, 3.0, 2), (2, 4.0, 3, 3, 2.0, 4), (1, 3.0, 1, 4, 2.0, 4), (2, 4.0, 2, 3, 3.0, 3), (3, 3.0, 3, 1, 4.0, 2), (3, 3.0, 3, 3, 4.0, 4), (4, 3.0, 2, 1, 2.0, 1), (3, 4.0, 2, 3, 3.0, 1), (3, 3.0, 4, 4, 4.0, 3), (1, 3.0, 4, 4, 2.0, 3), (3, 3.0, 3, 2, 1.0, 3), (3, 3.0, 1, 3, 2.0, 2), (2, 3.0, 2, 4, 2.0, 3), (4, 3.0, 4, 1, 4.0, 1), (3, 4.0, 1, 3, 2.0, 4), (1, 4.0, 4, 2, 3.0, 4), (4, 3.0, 2, 3, 3.0, 4), (1, 3.0, 2, 4, 3.0, 4), (2, 3.0, 1, 3, 3.0, 2), (3, 4.0, 3, 3, 3.0, 1), (2, 4.0, 4, 4, 2.0, 4), (1, 3.0, 3, 1, 3.0, 4), (3, 3.0, 4, 1, 4.0, 2), (2, 3.0, 1, 3, 4.0, 3), (1, 3.0, 4, 3, 1.0, 3), (3, 3.0, 3, 2, 4.0, 4), (4, 3.0, 3, 1, 3.0, 4), (2, 3.0, 2, 4, 3.0, 3), (3, 3.0, 1, 3, 3.0, 2), (3, 3.0, 2, 1, 1.0, 2), (2, 3.0, 4, 3, 3.0, 2), (1, 3.0, 1, 3, 2.0, 3), (3, 3.0, 4, 2, 3.0, 4), (2, 3.0, 3, 4, 4.0, 4), (2, 3.0, 4, 4, 2.0, 2), (1, 4.0, 1, 3, 2.0, 3), (3, 3.0, 2, 1, 4.0, 3), (2, 3.0, 4, 2, 2.0, 2), (2, 3.0, 3, 2, 3.0, 1), (2, 3.0, 1, 1, 3.0, 4), (3, 4.0, 1, 2, 1.0, 3), (3, 3.0, 1, 2, 3.0, 2), (1, 3.0, 2, 1, 2.0, 1), (4, 3.0, 4, 4, 4.0, 3), (3, 3.0, 1, 4, 3.0, 4), (3, 3.0, 3, 1, 3.0, 1), (3, 3.0, 2, 2, 1.0, 1), (3, 3.0, 3, 3, 3.0, 3), (2, 3.0, 4, 2, 3.0, 3), (2, 3.0, 3, 3, 2.0, 1), (2, 3.0, 4, 1, 2.0, 4), (3, 3.0, 3, 4, 4.0, 1), (1, 3.0, 2, 3, 3.0, 4), (3, 3.0, 4, 3, 2.0, 3), (2, 4.0, 3, 1, 3.0, 1), (3, 3.0, 4, 4, 3.0, 1), (4, 4.0, 2, 3, 1.0, 2), (3, 3.0, 3, 1, 4.0, 1), (2, 4.0, 1, 2, 4.0, 2), (3, 3.0, 3, 3, 4.0, 3), (4, 3.0, 1, 1, 4.0, 1), (4, 3.0, 4, 2, 3.0, 4), (2, 3.0, 2, 1, 3.0, 3), (2, 3.0, 3, 1, 1.0, 2), (3, 3.0, 3, 4, 1.0, 4), (3, 3.0, 1, 3, 2.0, 1), (3, 4.0, 3, 4, 2.0, 4), (4, 3.0, 4, 4, 3.0, 2), (4, 4.0, 3, 3, 3.0, 3), (3, 4.0, 4, 1, 3.0, 1), (3, 3.0, 4, 1, 4.0, 1), (2, 3.0, 3, 4, 3.0, 2), (3, 3.0, 2, 3, 3.0, 1), (3, 4.0, 3, 1, 1.0, 2), (4, 3.0, 3, 2, 1.0, 4), (2, 4.0, 1, 3, 3.0, 1), (3, 3.0, 2, 3, 4.0, 2), (1, 3.0, 3, 2, 2.0, 2), (2, 3.0, 1, 2, 3.0, 1), (4, 3.0, 4, 1, 3.0, 3), (3, 4.0, 4, 4, 2.0, 4), (1, 3.0, 3, 4, 3.0, 4), (3, 4.0, 1, 4, 3.0, 2), (2, 3.0, 4, 2, 2.0, 1), (2, 3.0, 1, 1, 3.0, 3), (4, 3.0, 3, 4, 3.0, 4), (3, 3.0, 1, 2, 3.0, 1), (3, 4.0, 3, 4, 1.0, 3), (3, 3.0, 2, 3, 2.0, 4), (3, 3.0, 1, 4, 3.0, 3), (1, 3.0, 4, 3, 4.0, 3), (3, 3.0, 3, 3, 3.0, 2), (3, 3.0, 2, 2, 4.0, 2), (3, 3.0, 2, 4, 4.0, 4), (2, 3.0, 4, 4, 1.0, 4), (4, 3.0, 3, 1, 2.0, 2), (3, 3.0, 4, 3, 4.0, 2), (2, 4.0, 1, 2, 4.0, 1), (4, 3.0, 3, 3, 3.0, 4), (3, 4.0, 2, 4, 3.0, 1), (3, 3.0, 1, 1, 3.0, 1), (3, 3.0, 1, 2, 2.0, 4), (2, 3.0, 2, 3, 3.0, 3), (2, 4.0, 3, 4, 3.0, 2), (3, 4.0, 3, 2, 4.0, 3), (2, 3.0, 2, 1, 3.0, 2), (1, 4.0, 3, 3, 4.0, 4), (3, 3.0, 3, 2, 3.0, 1), (3, 3.0, 4, 4, 2.0, 4), (2, 3.0, 1, 3, 2.0, 4), (3, 3.0, 3, 1, 3.0, 4), (2, 4.0, 4, 1, 1.0, 4), (2, 3.0, 3, 4, 3.0, 1), (3, 3.0, 3, 4, 4.0, 4), (3, 3.0, 2, 1, 3.0, 1), (2, 3.0, 3, 3, 4.0, 4), (4, 3.0, 1, 1, 3.0, 3), (2, 3.0, 4, 3, 2.0, 4), (3, 3.0, 1, 3, 1.0, 3), (3, 3.0, 1, 4, 2.0, 1), (2, 3.0, 2, 2, 3.0, 3), (4, 3.0, 2, 1, 4.0, 3), (4, 3.0, 4, 2, 2.0, 2), (2, 3.0, 3, 2, 2.0, 4), (2, 4.0, 3, 2, 3.0, 4), (3, 4.0, 1, 4, 3.0, 1), (2, 3.0, 1, 4, 1.0, 3), (3, 3.0, 2, 4, 3.0, 2), (3, 3.0, 2, 3, 2.0, 3), (4, 3.0, 1, 4, 3.0, 4), (3, 3.0, 4, 2, 1.0, 1), (2, 3.0, 4, 1, 4.0, 3), (3, 3.0, 4, 4, 1.0, 3), (3, 4.0, 2, 2, 2.0, 2), (1, 3.0, 1, 1, 3.0, 4), (1, 3.0, 4, 1, 3.0, 4), (2, 3.0, 1, 4, 2.0, 4), (3, 3.0, 3, 1, 2.0, 3), (3, 3.0, 2, 2, 4.0, 1), (3, 3.0, 2, 4, 4.0, 3), (3, 3.0, 2, 3, 3.0, 4), (3, 3.0, 3, 4, 3.0, 3), (2, 3.0, 4, 4, 1.0, 3), (4, 3.0, 3, 1, 2.0, 1), (1, 3.0, 3, 3, 3.0, 3), (1, 3.0, 2, 4, 2.0, 1), (2, 4.0, 4, 2, 3.0, 4), (3, 4.0, 4, 3, 3.0, 1), (3, 3.0, 4, 3, 4.0, 1), (4, 4.0, 1, 3, 3.0, 1), (4, 3.0, 3, 3, 3.0, 3), (3, 4.0, 3, 2, 3.0, 1), (1, 4.0, 2, 1, 2.0, 4), (3, 4.0, 1, 3, 4.0, 2), (2, 3.0, 4, 4, 4.0, 4), (4, 3.0, 3, 4, 2.0, 3), (3, 3.0, 4, 1, 2.0, 3), (2, 3.0, 2, 3, 3.0, 2), (3, 3.0, 2, 2, 3.0, 4), (1, 3.0, 1, 2, 2.0, 3), (4, 3.0, 4, 3, 3.0, 4), (2, 3.0, 1, 1, 2.0, 1), (3, 3.0, 4, 1, 3.0, 4), (2, 3.0, 1, 3, 2.0, 3), (3, 4.0, 3, 4, 4.0, 2), (2, 4.0, 1, 2, 3.0, 4), (3, 3.0, 4, 2, 4.0, 1), (3, 3.0, 1, 1, 1.0, 2), (2, 3.0, 3, 1, 4.0, 1), (3, 4.0, 1, 1, 2.0, 3), (4, 4.0, 1, 3, 2.0, 4), (2, 3.0, 3, 4, 2.0, 4), (3, 4.0, 3, 2, 2.0, 4), (3, 3.0, 1, 1, 2.0, 3), (1, 3.0, 1, 4, 3.0, 4), (2, 3.0, 2, 1, 2.0, 4), (2, 3.0, 2, 2, 3.0, 2), (4, 3.0, 1, 4, 2.0, 2), (2, 4.0, 3, 2, 3.0, 3), (2, 3.0, 4, 1, 3.0, 1), (4, 3.0, 4, 4, 2.0, 3), (3, 3.0, 2, 4, 3.0, 1), (2, 3.0, 3, 2, 4.0, 3), (4, 3.0, 2, 4, 3.0, 4), (3, 3.0, 2, 3, 2.0, 2), (3, 3.0, 1, 3, 4.0, 3), (4, 3.0, 1, 4, 3.0, 3), (3, 3.0, 4, 4, 1.0, 2), (3, 3.0, 3, 1, 2.0, 2), (3, 3.0, 3, 3, 2.0, 4), (1, 3.0, 3, 2, 3.0, 4), (2, 3.0, 1, 4, 4.0, 3), (3, 3.0, 3, 4, 3.0, 2), (4, 4.0, 1, 2, 3.0, 4), (2, 4.0, 4, 2, 3.0, 3), (2, 3.0, 4, 4, 3.0, 2), (4, 3.0, 1, 3, 2.0, 3), (3, 4.0, 3, 1, 3.0, 4), (3, 3.0, 1, 2, 1.0, 1), (3, 3.0, 1, 2, 4.0, 3), (3, 3.0, 2, 2, 2.0, 2), (2, 3.0, 4, 4, 4.0, 3), (2, 4.0, 3, 3, 3.0, 4), (2, 3.0, 3, 3, 3.0, 2), (2, 3.0, 1, 3, 1.0, 1), (3, 3.0, 4, 1, 2.0, 2), (2, 3.0, 4, 2, 4.0, 4), (3, 3.0, 3, 2, 2.0, 4), (3, 3.0, 2, 2, 3.0, 3), (4, 3.0, 4, 3, 3.0, 3), (1, 3.0, 2, 2, 3.0, 3), (2, 3.0, 3, 4, 2.0, 3), (2, 4.0, 2, 4, 3.0, 3), (3, 3.0, 2, 1, 2.0, 3), (2, 3.0, 4, 3, 4.0, 3), (3, 4.0, 3, 2, 2.0, 3), (3, 4.0, 2, 4, 2.0, 2), (1, 3.0, 1, 4, 3.0, 3), (3, 4.0, 4, 3, 3.0, 4), (3, 4.0, 1, 3, 3.0, 4), (2, 3.0, 3, 1, 2.0, 3), (2, 4.0, 3, 4, 2.0, 3), (1, 3.0, 2, 2, 4.0, 3), (3, 4.0, 4, 4, 4.0, 2), (2, 3.0, 1, 2, 2.0, 2), (4, 3.0, 2, 4, 2.0, 2), (2, 3.0, 3, 1, 3.0, 4), (2, 3.0, 1, 1, 1.0, 3), (2, 4.0, 4, 4, 3.0, 4), (3, 3.0, 3, 4, 2.0, 1), (3, 4.0, 3, 4, 3.0, 1), (3, 3.0, 1, 4, 1.0, 3), (2, 3.0, 3, 2, 4.0, 2), (3, 3.0, 3, 3, 1.0, 2), (4, 3.0, 2, 4, 3.0, 3), (3, 3.0, 2, 4, 2.0, 4), (2, 3.0, 1, 4, 3.0, 1), (2, 4.0, 1, 3, 4.0, 2), (1, 3.0, 1, 3, 3.0, 3), (1, 3.0, 1, 1, 3.0, 2), (1, 3.0, 4, 3, 3.0, 4), (3, 3.0, 4, 2, 4.0, 4), (3, 3.0, 4, 3, 3.0, 4), (3, 3.0, 3, 4, 3.0, 1), (3, 4.0, 4, 2, 3.0, 4), (3, 3.0, 4, 4, 4.0, 2), (2, 3.0, 4, 4, 3.0, 1), (3, 4.0, 3, 1, 3.0, 3), (4, 3.0, 4, 3, 2.0, 2), (4, 3.0, 2, 3, 3.0, 3), (2, 4.0, 3, 4, 1.0, 2), (3, 3.0, 1, 4, 4.0, 4), (4, 3.0, 2, 2, 2.0, 4), (4, 3.0, 3, 4, 2.0, 1), (1, 3.0, 4, 4, 3.0, 3), (2, 3.0, 3, 3, 3.0, 1), (1, 4.0, 3, 3, 2.0, 4), (3, 3.0, 3, 2, 2.0, 3), (3, 3.0, 2, 3, 1.0, 1), (4, 3.0, 3, 1, 1.0, 3), (2, 3.0, 2, 3, 2.0, 4), (2, 3.0, 1, 3, 4.0, 2), (2, 3.0, 2, 4, 3.0, 2), (3, 3.0, 1, 3, 3.0, 1), (2, 3.0, 4, 3, 3.0, 1), (3, 3.0, 4, 2, 3.0, 3), (2, 3.0, 4, 3, 4.0, 2), (3, 4.0, 2, 1, 3.0, 2), (2, 3.0, 3, 1, 2.0, 2), (3, 3.0, 1, 1, 4.0, 1), (2, 4.0, 4, 4, 3.0, 3), (2, 3.0, 3, 1, 3.0, 3), (3, 4.0, 3, 3, 3.0, 4), (2, 3.0, 4, 2, 3.0, 2), (2, 3.0, 3, 2, 4.0, 1), (3, 3.0, 3, 3, 1.0, 1), (2, 3.0, 4, 1, 2.0, 3), (3, 4.0, 1, 2, 2.0, 3), (3, 3.0, 2, 4, 2.0, 3), (1, 3.0, 2, 3, 3.0, 3), (3, 3.0, 4, 3, 2.0, 2), (1, 3.0, 3, 3, 1.0, 3), (3, 3.0, 4, 3, 3.0, 3), (3, 3.0, 3, 3, 4.0, 2), (4, 3.0, 2, 3, 2.0, 1), (3, 4.0, 4, 4, 3.0, 4), (4, 3.0, 2, 3, 3.0, 2), (2, 3.0, 3, 2, 3.0, 4), (4, 4.0, 2, 3, 3.0, 3), (1, 3.0, 2, 1, 2.0, 4), (3, 3.0, 3, 2, 2.0, 2), (1, 3.0, 3, 1, 3.0, 2), (3, 3.0, 3, 4, 2.0, 4), (3, 3.0, 4, 1, 1.0, 4), (3, 4.0, 3, 4, 3.0, 4)]

In [11]:
# INSERTAMOS LOS DATOS EN LA TABLA SATISFACTION SURVEYS

cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()
query_insercion_satisfaction = """INSERT INTO satisfaction_surveys (
                                    JobInvolvement, 
                                    PerformanceRating, 
                                    EnvironmentSatisfaction, 
                                    RelationshipSatisfaction, 
                                    WorkLifeBalance, 
                                    JobSatisfaction) 
                                    VALUES (%s, %s, %s, %s, %s, %s)"""

try:
    mycursor.executemany(query_insercion_satisfaction,valores_tabla_satisfaction)
    cnx.commit()
    print(mycursor.rowcount, "registros insertados")
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

624 registros insertados

In [12]:
# PARA PODER RECOGER LOS DATOS NECESARIOS PARA EL DF EMPLOYEE HACEMOS UN FETCHALL PARA RECOGER LOS DATOS DE LAS TABLAS CREADAS
# Y PODER INCORPORARLO A NUESTRO DATAFRAME PARA HACER LA INSERCION EN EMPLOYEES

cnx = mysql.connector.connect(user = "root", password = 'AlumnaAdalab', host ="127.0.0.1", database = 'Proyecto')

mycursor = cnx.cursor()

query = ("SELECT * FROM work")

mycursor.execute(query)

datos_work = mycursor.fetchall()
    
cnx.close()
    
dataframe_work = pd.DataFrame(datos_work, columns = ['idWork', 'JobLevel', 'JobRole', 'Department'])
     
df_employees_work = pd.merge(df, dataframe_work, on = ['JobLevel', 'JobRole', 'Department'])

print("filas y columnas", df_employees_work.shape)

df_employees_work

filas y columnas (1486, 28)

,EmployeeNumber,Age,Gender,Education,EducationField,NumCompaniesWorked,JobLevel,JobRole,Department,JobInvolvement,PerformanceRating,Attrition,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,MonthlyIncome,StockOptionLevel,PercentSalaryHike,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,TrainingTimesLastYear,BusinessTravel,DistanceFromHome,OverTime,RemoteWork,idWork
0,162.0,51,Male,3,NaN,7,5,Research Director,Unknown,3,3.0,No,3,1.0,3,3.0,19537.0,0,13,20,15,15,5,Non-Travel,6,No,Yes,53
1,259.0,52,Male,4,Life Sciences,0,5,Manager,Unknown,2,3.0,No,3,3.0,1,3.0,19999.0,1,14,33,11,9,5,Non-Travel,1,No,Yes,52
2,319.0,42,Male,2,Technical Degree,1,5,Manager,Research & Development,3,3.0,No,4,3.0,4,3.0,19232.0,0,11,22,11,15,3,travel_rarely,4,No,Yes,34
3,Unknown,47,Female,4,Medical,3,4,Research Director,Unknown,3,3.0,No,3,1.0,2,3.0,17169.0,2,19,20,5,6,2,travel_rarely,2,No,No,50
4,Unknown,46,Female,3,Technical Degree,2,4,Sales Executive,Unknown,4,3.0,No,1,1.0,4,3.0,12528.4,1,12,19,2,8,5,Non-Travel,3,No,No,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,913.0,44,Male,2,NaN,1,1,Research Scientist,Unknown,3,3.0,No,1,2.0,4,3.0,NaN,0,13,8,7,1,0,Non-Travel,9,Yes,No,48
1482,956.0,26,Male,3,Medical,1,2,Sales Executive,Sales,2,3.0,No,1,3.0,2,3.0,NaN,0,12,7,0,7,2,travel_frequently,1,No,Yes,37
1483,Unknown,31,Female,3,Medical,0,2,Healthcare Representative,Unknown,3,3.0,No,4,4.0,3,1.0,NaN,2,11,9,8,5,2,Non-Travel,12,No,Yes,38
1484,972.0,45,Male,2,NaN,1,2,Laboratory Technician,Unknown,3,3.0,No,2,3.0,2,2.0,NaN,0,12,9,0,8,5,non-travel,4,No,Yes,28
1485,Unknown,39,Male,5,NaN,0,3,Sales Executive,Unknown,4,3.0,No,3,3.0,4,3.0,NaN,0,18,8,0,7,3,travel_rarely,13,No,Yes,18

In [13]:
# HACEMOS LO MISMO PARA RECOGER LOS DATOS DE SATISFACTION SURVEYS

cnx = mysql.connector.connect(user = "root", password = 'AlumnaAdalab', host ="127.0.0.1", database = 'Proyecto')

mycursor = cnx.cursor()

query = ("SELECT * FROM satisfaction_surveys")

mycursor.execute(query)

datos_satisfaction = mycursor.fetchall()
    
cnx.close()
    
dataframe_satisfaction = pd.DataFrame(datos_satisfaction, columns = ['idSatisfaction', 'JobInvolvement', 'PerformanceRating', 'EnvironmentSatisfaction', 'RelationshipSatisfaction', 'WorkLifeBalance', 'JobSatisfaction'])
     
df_employees_completo = pd.merge(df_employees_work, dataframe_satisfaction, on = ['JobInvolvement', 'PerformanceRating', 'EnvironmentSatisfaction', 'RelationshipSatisfaction', 'WorkLifeBalance', 'JobSatisfaction'])

print("filas y columnas", df_employees_completo.shape)

df_employees_completo

filas y columnas (1486, 29)

,EmployeeNumber,Age,Gender,Education,EducationField,NumCompaniesWorked,JobLevel,JobRole,Department,JobInvolvement,PerformanceRating,Attrition,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,MonthlyIncome,StockOptionLevel,PercentSalaryHike,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,TrainingTimesLastYear,BusinessTravel,DistanceFromHome,OverTime,RemoteWork,idWork,idSatisfaction
0,162.0,51,Male,3,NaN,7,5,Research Director,Unknown,3,3.0,No,3,1.0,3,3.0,19537.0,0,13,20,15,15,5,Non-Travel,6,No,Yes,53,301
1,259.0,52,Male,4,Life Sciences,0,5,Manager,Unknown,2,3.0,No,3,3.0,1,3.0,19999.0,1,14,33,11,9,5,Non-Travel,1,No,Yes,52,601
2,319.0,42,Male,2,Technical Degree,1,5,Manager,Research & Development,3,3.0,No,4,3.0,4,3.0,19232.0,0,11,22,11,15,3,travel_rarely,4,No,Yes,34,231
3,Unknown,47,Female,4,Medical,3,4,Research Director,Unknown,3,3.0,No,3,1.0,2,3.0,17169.0,2,19,20,5,6,2,travel_rarely,2,No,No,50,316
4,Unknown,46,Female,3,Technical Degree,2,4,Sales Executive,Unknown,4,3.0,No,1,1.0,4,3.0,12528.4,1,12,19,2,8,5,Non-Travel,3,No,No,15,195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,913.0,44,Male,2,NaN,1,1,Research Scientist,Unknown,3,3.0,No,1,2.0,4,3.0,NaN,0,13,8,7,1,0,Non-Travel,9,Yes,No,48,511
1482,956.0,26,Male,3,Medical,1,2,Sales Executive,Sales,2,3.0,No,1,3.0,2,3.0,NaN,0,12,7,0,7,2,travel_frequently,1,No,Yes,37,368
1483,Unknown,31,Female,3,Medical,0,2,Healthcare Representative,Unknown,3,3.0,No,4,4.0,3,1.0,NaN,2,11,9,8,5,2,Non-Travel,12,No,Yes,38,102
1484,972.0,45,Male,2,NaN,1,2,Laboratory Technician,Unknown,3,3.0,No,2,3.0,2,2.0,NaN,0,12,9,0,8,5,non-travel,4,No,Yes,28,620
1485,Unknown,39,Male,5,NaN,0,3,Sales Executive,Unknown,4,3.0,No,3,3.0,4,3.0,NaN,0,18,8,0,7,3,travel_rarely,13,No,Yes,18,23

In [14]:
# RECOGEMOS LOS VALORES QUE NOS INTERESAN DEL DATAFRAME COMPLETO PARA INSERTARLOS EN LA TABLA EMPLOYEES

valores_tabla_employee = list(zip(
    df_employees_completo['EmployeeNumber'].values,
    [int(x) for x in df_employees_completo['Age'].values],
    df_employees_completo['Gender'].values,   
    [int(x) for x in df_employees_completo['Education'].values], 
    df_employees_completo['EducationField'].values, 
    [int(x) for x in df_employees_completo['NumCompaniesWorked'].values],
    [float(x) for x in df_employees_completo['MonthlyIncome'].values],
    [int(x) for x in df_employees_completo['StockOptionLevel'].values],
    [int(x) for x in df_employees_completo['YearsAtCompany'].values],
    [int(x) for x in df_employees_completo['YearsSinceLastPromotion'].values], 
    [int(x) for x in df_employees_completo['YearsWithCurrManager'].values],
    [int(x) for x in df_employees_completo['TrainingTimesLastYear'].values], 
    [int(x) for x in df_employees_completo['DistanceFromHome'].values],
    df_employees_completo['Attrition'].values, 
    [int(x) for x in df_employees_completo['idWork'].values],
    [int(x) for x in df_employees_completo['idSatisfaction']]
))

print(valores_tabla_employee)

[('162.0', 51, 'Male', 3, nan, 7, 19537.0, 0, 20, 15, 15, 5, 6, 'No', 53, 301), ('259.0', 52, 'Male', 4, 'Life Sciences', 0, 19999.0, 1, 33, 11, 9, 5, 1, 'No', 52, 601), ('319.0', 42, 'Male', 2, 'Technical Degree', 1, 19232.0, 0, 22, 11, 15, 3, 4, 'No', 34, 231), ('Unknown', 47, 'Female', 4, 'Medical', 3, 17169.0, 2, 20, 5, 6, 2, 2, 'No', 50, 316), ('Unknown', 46, 'Female', 3, 'Technical Degree', 2, 12528.4, 1, 19, 2, 8, 5, 3, 'No', 15, 195), ('1900.0', 48, 'Female', 3, 'Medical', 3, 17174.0, 1, 22, 4, 7, 3, 22, 'No', 26, 362), ('81.0', 59, 'Female', 3, 'Life Sciences', 7, 10148.8, 0, 21, 7, 9, 3, 25, 'No', 18, 449), ('387.0', 42, 'Male', 1, nan, 1, 5805.2, 0, 20, 11, 6, 3, 1, 'No', 39, 16), ('Unknown', 41, 'Female', 5, nan, 7, 16595.0, 1, 18, 11, 8, 2, 2, 'No', 41, 221), ('999.0', 41, 'Male', 3, nan, 2, 17947.2, 1, 18, 0, 11, 2, 9, 'No', 53, 529), ('1035.0', 41, 'Female', 1, nan, 1, 19973.0, 2, 21, 5, 10, 3, 7, 'No', 53, 227), ('Unknown', 56, 'Male', 3, 'Life Sciences', 4, 13402.0, 1, 19, 15, 9, 0, 23, 'No', 1, 167), ('Unknown', 38, 'Female', 3, 'Medical', 3, 13206.0, 1, 18, 1, 11, 3, 10, 'No', 54, 326), ('58.0', 41, 'Female', 3, nan, 1, 19545.0, 0, 22, 15, 8, 0, 12, 'Yes', 53, 223), ('Unknown', 55, 'Male', 4, 'Medical', 8, 16968.2, 0, 24, 2, 15, 3, 14, 'No', 53, 85), ('558.0', 40, 'Female', 4, nan, 0, 18041.0, 0, 20, 1, 12, 2, 2, 'No', 52, 471), ('825.0', 58, 'Male', 4, nan, 7, 19246.0, 0, 31, 13, 8, 2, 2, 'Yes', 53, 330), ('Unknown', 46, 'Female', 3, nan, 8, 17688.0, 0, 26, 15, 9, 2, 2, 'No', 41, 261), ('Unknown', 35, 'Male', 5, 'Life Sciences', 1, 4504.0, 0, 16, 1, 10, 2, 13, 'No', 43, 246), ('Unknown', 40, 'Female', 3, 'Life Sciences', 1, 7712.6, 2, 18, 14, 12, 2, 15, 'No', 7, 278), ('1712.0', 45, 'Male', 1, nan, 3, 10748.0, 1, 23, 14, 4, 3, 1, 'No', 8, 551), ('73.0', 33, 'Female', 2, 'Life Sciences', 1, 7074.0, 0, 15, 8, 12, 1, 1, 'No', 54, 248), ('Unknown', 36, 'Female', 3, nan, 1, 9080.0, 3, 17, 12, 8, 2, 8, 'No', 24, 136), ('820.0', 47, 'Female', 2, 'Other', 1, 16752.0, 1, 26, 3, 0, 3, 2, 'No', 41, 519), ('Unknown', 36, 'Male', 2, 'Life Sciences', 1, 6201.0, 1, 18, 4, 11, 1, 42, 'No', 39, 231), ('Unknown', 35, 'Female', 3, 'Life Sciences', 1, 8251.6, 1, 17, 5, 15, 2, 9, 'No', 7, 524), ('Unknown', 52, 'Female', 1, nan, 1, 19845.0, 1, 32, 6, 9, 3, 2, 'Yes', 52, 504), ('1294.0', 36, 'Female', 4, 'Life Sciences', 9, 5261.4, 0, 16, 5, 12, 2, 2, 'No', 20, 522), ('Unknown', 33, 'Male', 4, 'Life Sciences', 1, 5364.0, 1, 15, 5, 7, 3, 28, 'No', 28, 538), ('1774.0', 34, 'Male', 3, 'Life Sciences', 1, 4001.0, 1, 15, 0, 7, 3, 10, 'No', 37, 612), ('1815.0', 41, 'Female', 1, nan, 0, 10447.0, 1, 22, 13, 5, 3, 37, 'No', 17, 66), ('1993.0', 47, 'Male', 3, 'Medical', 2, 8665.4, 0, 17, 12, 11, 3, 25, 'No', 8, 218), ('32.0', 53, 'Female', 3, nan, 4, 16839.0, 1, 14, 4, 8, 3, 5, 'No', 52, 272), ('100.0', 35, 'Male', 4, 'Marketing', 0, 5395.2, 0, 15, 2, 8, 2, 1, 'No', 39, 368), ('Unknown', 34, 'Female', 4, 'Other', 1, 4484.6, 0, 16, 2, 10, 3, 6, 'No', 43, 301), ('244.0', 46, 'Female', 2, nan, 1, 8551.6, 3, 24, 15, 7, 2, 1, 'No', 18, 337), ('327.0', 43, 'Female', 3, nan, 5, 16064.0, 1, 17, 1, 9, 3, 16, 'No', 41, 548), ('373.0', 36, 'Male', 3, 'Life Sciences', 0, 3210.0, 1, 15, 10, 11, 4, 6, 'No', 6, 572), ('Unknown', 60, 'Female', 3, nan, 4, 10266.0, 0, 18, 13, 11, 5, 28, 'No', 18, 72), ('729.0', 40, 'Male', 4, nan, 5, 10475.0, 1, 18, 1, 12, 2, 5, 'No', 18, 282), ('830.0', 32, 'Female', 3, nan, 1, 6162.0, 1, 14, 6, 8, 3, 4, 'No', 20, 292), ('Unknown', 41, 'Male', 3, nan, 2, 4721.0, 0, 18, 2, 17, 3, 35, 'No', 25, 28), ('981.0', 53, 'Male', 2, 'Medical', 6, 15858.0, 1, 17, 15, 2, 3, 2, 'No', 41, 389), ('1042.0', 36, 'Female', 4, nan, 1, 3144.2, 0, 17, 15, 14, 1, 16, 'Yes', 25, 152), ('1080.0', 46, 'Female', 4, 'Life Sciences', 8, 4615.0, 3, 16, 1, 7, 2, 8, 'No', 43, 174), ('1995.0', 38, 'Male', 4, nan, 0, 7346.8, 2, 15, 5, 8, 3, 1, 'No', 39, 167), ('145.0', 51, 'Female', 4, nan, 3, 9934.6, 0, 13, 12, 8, 1, 1, 'No', 24, 143), ('158.0', 43, 'Male', 2, nan, 1, 16959.0, 2, 25, 4, 12, 3, 26, 'No', 41, 443), ('391.0', 37, 'Female', 3, 'Life Sciences', 1, 3976.8, 0, 17, 5, 7, 3, 1, 'No', 48, 362), ('436.0', 32, 'Female', 2, 'Technical Degree', 1, 5830.8, 0, 13, 11, 9, 2, 8, 'No', 39, 401), ('Unknown', 38, 'Female', 3, nan, 1, 10343.2, 1, 15, 5, 11, 3, 1, 'No', 54, 279), ('1527.0', 46, 'Female', 3, 'Life Sciences', 8, 17688.0, 1, 13, 5, 1, 2, 3, 'No', 41, 117), ('Unknown', 35, 'Male', 3, 'Medical', 9, 10306.0, 0, 13, 6, 0, 3, 10, 'Yes', 18, 594), ('1866.0', 43, 'Female', 3, 'Medical', 7, 18302.0, 0, 16, 6, 14, 2, 6, 'No', 52, 278), ('2026.0', 56, 'Male', 4, 'Life Sciences', 1, 6373.6, 1, 13, 1, 9, 2, 1, 'No', 38, 467), ('Unknown', 36, 'Male', 4, 'Marketing', 1, 5406.0, 1, 15, 11, 11, 4, 15, 'No', 39, 148), ('107.0', 38, 'Female', 3, 'Medical', 7, 4982.4, 3, 13, 1, 9, 3, 6, 'No', 43, 347), ('170.0', 49, 'Female', 4, 'Medical', 1, 6372.0, 0, 15, 5, 11, 2, 26, 'No', 20, 250), ('Unknown', 39, 'Female', 4, 'Life Sciences', 4, 5902.0, 1, 15, 5, 9, 1, 4, 'No', 39, 544), ('215.0', 40, 'Male', 4, nan, 7, 10855.0, 1, 12, 2, 11, 2, 4, 'No', 18, 311), ('304.0', 36, 'Male', 2, nan, 8, 5914.0, 0, 13, 3, 7, 3, 5, 'No', 28, 575), ('529.0', 37, 'Female', 5, nan, 3, 4166.8, 2, 13, 10, 7, 2, 25, 'No', 43, 147), ('691.0', 35, 'Male', 4, nan, 1, 6646.0, 0, 17, 11, 8, 3, 6, 'No', 43, 302), ('692.0', 33, 'Male', 3, 'Life Sciences', 3, 5201.8, 1, 13, 4, 7, 2, 6, 'No', 38, 186), ('1005.0', 50, 'Male', 3, nan, 3, 13973.0, 1, 12, 1, 5, 2, 24, 'No', 44, 74), ('1024.0', 48, 'Male', 4, nan, 7, 10704.2, 0, 15, 4, 8, 3, 4, 'No', 24, 265), ('1039.0', 44, 'Female', 3, nan, 3, 13320.0, 1, 12, 11, 11, 2, 28, 'No', 13, 490), ('1225.0', 44, 'Male', 4, nan, 1, 4460.2, 0, 20, 13, 17, 3, 29, 'No', 43, 574), ('1375.0', 40, 'Female', 1, nan, 5, 6538.8, 3, 12, 11, 8, 0, 25, 'No', 38, 214), ('Unknown', 34, 'Female', 4, nan, 1, 6687.0, 0, 14, 4, 11, 2, 2, 'No', 38, 443), ('Unknown', 35, 'Female', 4, nan, 1, 5627.0, 1, 14, 2, 9, 5, 8, 'No', 21, 471), ('Unknown', 50, 'Female', 5, 'Life Sciences', 5, 13131.6, 3, 14, 1, 11, 3, 17, 'No', 54, 594), ('1661.0', 49, 'Female', 1, 'Life Sciences', 2, 13694.2, 1, 15, 2, 12, 3, 6, 'No', 23, 265), ('1668.0', 38, 'Male', 3, 'Life Sciences', 7, 4735.0, 2, 13, 2, 9, 4, 1, 'No', 43, 12), ('1698.0', 33, 'Male', 3, nan, 1, 2824.6, 3, 14, 2, 13, 6, 21, 'No', 25, 191), ('Unknown', 47, 'Female', 3, 'Life Sciences', 8, 7374.8, 1, 22, 14, 10, 4, 4, 'No', 7, 533), ('1937.0', 38, 'Female', 3, nan, 1, 4982.4, 1, 20, 0, 7, 3, 8, 'No', 29, 360), ('2017.0', 37, 'Female', 3, 'Life Sciences', 1, 11390.4, 1, 16, 6, 8, 2, 10, 'No', 54, 307), ('117.0', 30, 'Male', 3, nan, 1, 6112.0, 3, 11, 10, 8, 3, 2, 'No', 38, 556), ('131.0', 58, 'Male', 4, nan, 0, 13872.0, 0, 37, 1, 8, 1, 18, 'No', 15, 383), ('153.0', 34, 'Female', 3, nan, 2, 8350.6, 0, 11, 5, 8, 6, 5, 'No', 47, 442), ('Unknown', 58, 'Female', 4, 'Medical', 1, 10414.0, 1, 40, 15, 6, 3, 23, 'Yes', 24, 438), ('307.0', 38, 'Male', 3, 'Life Sciences', 0, 7983.6, 2, 16, 5, 13, 6, 3, 'No', 18, 83), ('Unknown', 29, 'Female', 1, nan, 1, 6178.0, 1, 11, 4, 1, 5, 1, 'No', 18, 165), ('374.0', 55, 'Male', 3, 'Medical', 0, 19045.0, 0, 36, 4, 13, 2, 1, 'No', 52, 306), ('Unknown', 41, 'Male', 4, nan, 1, 16015.0, 0, 22, 0, 4, 2, 10, 'No', 41, 9), ('Unknown', 39, 'Male', 3, nan, 0, 9613.0, 3, 18, 3, 7, 5, 1, 'No', 8, 119), ('Unknown', 38, 'Male', 2, 'Life Sciences', 0, 11510.0, 1, 11, 2, 9, 3, 15, 'No', 54, 617), ('Unknown', 43, 'Male', 3, nan, 1, 15915.0, 1, 25, 3, 9, 3, 12, 'No', 50, 348), ('569.0', 50, 'Male', 4, 'Life Sciences', 0, 8251.6, 1, 27, 15, 7, 2, 27, 'No', 26, 265), ('899.0', 35, 'Male', 3, 'Technical Degree', 3, 5067.0, 0, 13, 4, 8, 2, 25, 'No', 7, 271), ('Unknown', 47, 'Male', 4, nan, 1, 6524.8, 0, 19, 2, 7, 3, 16, 'No', 20, 480), ('1014.0', 35, 'Female', 4, nan, 1, 11854.0, 1, 16, 10, 1, 3, 25, 'No', 8, 142), ('Unknown', 40, 'Male', 4, nan, 4, 4979.4, 1, 11, 11, 1, 6, 20, 'No', 24, 109), ('1117.0', 45, 'Female', 4, 'Life Sciences', 1, 2947.0, 1, 15, 4, 12, 2, 9, 'No', 37, 357), ('1238.0', 33, 'Male', 3, 'Medical', 0, 3692.0, 1, 14, 4, 10, 5, 9, 'No', 31, 61), ('Unknown', 36, 'Male', 3, nan, 1, 18835.8, 0, 11, 0, 7, 2, 3, 'No', 48, 198), ('1277.0', 45, 'Female', 3, 'Marketing', 2, 19847.0, 0, 24, 1, 11, 2, 13, 'Yes', 52, 569), ('Unknown', 51, 'Male', 3, nan, 4, 2308.0, 1, 29, 11, 10, 5, 27, 'No', 52, 518), ('1541.0', 34, 'Male', 2, 'Technical Degree', 0, 15981.4, 1, 11, 5, 7, 4, 7, 'No', 10, 38), ('1666.0', 43, 'Male', 2, nan, 1, 4793.2, 1, 14, 6, 11, 3, 15, 'No', 33, 70), ('1696.0', 34, 'Male', 2, 'Medical', 1, 4238.6, 1, 15, 4, 13, 3, 5, 'No', 28, 190), ('1805.0', 38, 'Male', 3, nan, 5, 16841.8, 3, 11, 3, 8, 3, 2, 'No', 22, 25), ('Unknown', 48, 'Male', 3, nan, 4, 5747.0, 0, 22, 12, 9, 3, 10, 'No', 53, 525), ('1932.0', 34, 'Male', 4, 'Other', 1, 10422.0, 0, 15, 6, 11, 3, 22, 'No', 29, 617), ('2016.0', 32, 'Female', 4, nan, 1, 8423.0, 2, 14, 5, 7, 3, 31, 'No', 18, 114), ('20.0', 29, 'Female', 4, 'Life Sciences', 1, 9629.2, 1, 10, 8, 8, 1, 21, 'No', 7, 56), ('Unknown', 46, 'Male', 3, 'Medical', 2, 6347.0, 1, 10, 9, 5, 5, 1, 'No', 24, 379), ('184.0', 30, 'Male', 3, nan, 0, 2348.0, 0, 11, 4, 7, 2, 9, 'No', 4, 394), ('206.0', 45, 'Male', 3, 'Life Sciences', 8, 7034.8, 1, 17, 0, 15, 2, 9, 'No', 28, 146), ('228.0', 30, 'Female', 3, nan, 2, 3072.0, 1, 10, 7, 4, 2, 5, 'No', 18, 470), ('239.0', 30, 'Male', 3, nan, 1, 5866.6, 2, 12, 6, 10, 4, 9, 'No', 28, 28), ('256.0', 34, 'Male', 1, nan, 1, 12490.0, 0, 10, 1, 9, 2, 29, 'No', 20, 73), ('Unknown', 51, 'Male', 4, 'Life Sciences', 5, 5890.8, 2, 10, 4, 7, 5, 8, 'No', 54, 125), ('339.0', 34, 'Male', 4, 'Life Sciences', 6, 8020.0, 1, 11, 5, 9, 3, 39, 'No', 20, 368), ('406.0', 35, 'Male', 3, nan, 0, 7425.2, 2, 11, 6, 9, 3, 16, 'No', 18, 198), ('Unknown', 45, 'Male', 3, 'Life Sciences', 1, 17068.0, 1, 24, 9, 11, 2, 7, 'No', 3, 430), ('429.0', 39, 'Male', 1, nan, 1, 8943.0, 0, 21, 11, 10, 3, 10, 'No', 41, 573), ('Unknown', 31, 'Female', 2, nan, 1, 19272.0, 1, 10, 8, 9, 2, 7, 'No', 7, 70), ('444.0', 39, 'Male', 2, nan, 1, 4913.8, 1, 21, 13, 3, 2, 7, 'No', 34, 556), ('452.0', 45, 'Male', 4, nan, 9, 6083.2, 2, 10, 9, 8, 3, 8, 'No', 43, 492), ('456.0', 30, 'Female', 3, 'Marketing', 1, 7676.6, 3, 10, 1, 2, 2, 5, 'No', 37, 303), ('Unknown', 31, 'Female', 4, 'Medical', 1, 6946.6, 0, 11, 4, 10, 2, 7, 'No', 7, 519), ('481.0', 36, 'Male', 4, 'Medical', 4, 7439.2, 1, 13, 1, 12, 2, 3, 'No', 18, 369), ('513.0', 36, 'Male', 2, nan, 1, 14798.4, 2, 10, 9, 0, 2, 2, 'No', 18, 450), ('597.0', 55, 'Female', 5, nan, 3, 5562.2, 0, 10, 7, 7, 2, 18, 'No', 41, 412), ('600.0', 35, 'Male', 3, nan, 9, 9001.2, 0, 11, 6, 9, 2, 1, 'No', 39, 97), ('Unknown', 42, 'Male', 3, 'Medical', 1, 5577.0, 1, 10, 5, 8, 5, 24, 'No', 7, 129), ('630.0', 52, 'Male', 2, nan, 3, 18395.6, 2, 10, 6, 9, 3, 6, 'No', 43, 279), ('638.0', 49, 'Male', 4, 'Life Sciences', 1, 2691.0, 1, 31, 0, 9, 5, 18, 'No', 53, 303), ('683.0', 34, 'Male', 5, nan, 1, 2876.8, 1, 10, 8, 8, 4, 1, 'No', 31, 565), ('780.0', 33, 'Male', 4, 'Other', 1, 8255.6, 0, 10, 7, 8, 2, 1, 'Yes', 48, 328), ('817.0', 33, 'Male', 3, 'Medical', 0, 16064.8, 0, 13, 3, 7, 3, 7, 'No', 40, 66), ('901.0', 53, 'Female', 4, nan, 6, 7403.0, 0, 12, 3, 8, 0, 23, 'No', 50, 572), ('944.0', 49, 'Female', 2, 'Other', 4, 7376.0, 1, 26, 1, 7, 3, 8, 'No', 3, 341), ('984.0', 35, 'Male', 4, nan, 6, 8823.0, 1, 10, 0, 8, 2, 21, 'No', 18, 88), ('1088.0', 38, 'Female', 1, 'Life Sciences', 0, 15179.4, 1, 19, 1, 9, 4, 17, 'No', 24, 550), ('1124.0', 46, 'Male', 1, 'Marketing', 3, 5261.4, 1, 12, 4, 9, 3, 3, 'No', 42, 419), ('Unknown', 36, 'Male', 4, nan, 2, 10253.4, 0, 11, 0, 9, 0, 18, 'No', 20, 32), ('1167.0', 42, 'Male', 3, 'Life Sciences', 0, 6695.4, 0, 21, 13, 14, 2, 15, 'Yes', 15, 269), ('1184.0', 34, 'Male', 3, nan, 0, 3579.0, 0, 13, 4, 9, 3, 1, 'No', 38, 282), ('Unknown', 30, 'Male', 3, 'Medical', 0, 17779.0, 1, 11, 5, 7, 2, 1, 'No', 31, 144), ('Unknown', 54, 'Male', 3, 'Life Sciences', 3, 7132.2, 0, 10, 0, 9, 2, 3, 'No', 50, 492), ('1252.0', 31, 'Female', 3, 'Medical', 1, 18213.0, 0, 10, 1, 8, 2, 24, 'No', 38, 368), ('1267.0', 44, 'Male', 3, nan, 7, 13577.0, 1, 22, 3, 10, 5, 5, 'No', 52, 146), ('1278.0', 55, 'Male', 1, nan, 1, 19190.0, 1, 33, 15, 0, 3, 8, 'No', 23, 525), ('1288.0', 44, 'Male', 2, 'Life Sciences', 1, 4885.4, 2, 25, 14, 13, 4, 4, 'No', 52, 583), ('Unknown', 34, 'Male', 3, 'Life Sciences', 4, 17123.0, 2, 10, 1, 8, 5, 11, 'No', 4, 10), ('1307.0', 39, 'Female', 4, nan, 6, 19187.0, 2, 19, 15, 2, 4, 13, 'No', 41, 401), ('1336.0', 55, 'Female', 2, 'Medical', 4, 16957.8, 1, 19, 9, 11, 5, 2, 'No', 52, 584), ('1352.0', 51, 'Male', 3, 'Life Sciences', 1, 10008.0, 1, 33, 0, 10, 2, 5, 'No', 41, 192), ('1360.0', 58, 'Female', 4, 'Medical', 7, 9682.8, 0, 10, 5, 9, 0, 14, 'Yes', 7, 230), ('Unknown', 48, 'Male', 3, 'Life Sciences', 1, 7988.0, 0, 10, 0, 8, 2, 4, 'No', 7, 572), ('1419.0', 29, 'Male', 3, nan, 1, 5365.8, 0, 10, 0, 9, 3, 17, 'No', 35, 234), ('1478.0', 34, 'Male', 3, 'Other', 3, 3466.8, 0, 13, 3, 12, 2, 3, 'No', 39, 268), ('1480.0', 42, 'Female', 2, nan, 1, 5424.6, 0, 12, 5, 8, 3, 9, 'No', 25, 248), ('Unknown', 57, 'Male', 2, 'Life Sciences', 0, 5821.8, 1, 12, 2, 8, 2, 1, 'No', 43, 79), ('1489.0', 34, 'Female', 4, nan, 0, 16785.0, 0, 15, 10, 10, 2, 24, 'Yes', 39, 567), ('1520.0', 54, 'Female', 4, 'Medical', 3, 7083.0, 1, 14, 1, 12, 2, 11, 'No', 41, 99), ('1535.0', 34, 'Male', 3, nan, 1, 4723.0, 0, 10, 8, 6, 3, 1, 'No', 18, 284), ('1586.0', 29, 'Male', 1, 'Medical', 1, 3407.0, 0, 10, 1, 5, 3, 3, 'No', 25, 511), ('1596.0', 35, 'Male', 3, 'Life Sciences', 1, 5395.2, 2, 10, 6, 8, 3, 28, 'No', 28, 317), ('1667.0', 35, 'Male', 4, 'Other', 3, 2929.0, 0, 11, 6, 7, 2, 12, 'Yes', 39, 45), ('1701.0', 34, 'Female', 3, 'Life Sciences', 1, 6796.0, 0, 10, 8, 7, 3, 19, 'No', 48, 213), ('1706.0', 43, 'Male', 3, nan, 1, 15248.0, 1, 10, 8, 8, 3, 2, 'No', 39, 492), ('Unknown', 58, 'Male', 3, 'Medical', 4, 6357.0, 1, 16, 14, 14, 0, 2, 'No', 41, 546), ('Unknown', 36, 'Female', 4, nan, 1, 10396.6, 1, 10, 1, 7, 4, 14, 'No', 37, 601), ('1971.0', 43, 'Male', 3, 'Life Sciences', 1, 17340.0, 1, 10, 0, 9, 1, 11, 'No', 24, 316), ('Unknown', 55, 'Male', 4, 'Human Resources', 4, 5086.2, 1, 10, 1, 4, 0, 26, 'No', 52, 3), ('1976.0', 42, 'Male', 2, nan, 1, 4333.8, 0, 20, 3, 7, 2, 23, 'No', 29, 284), ('1985.0', 40, 'Female', 3, 'Technical Degree', 1, 4287.0, 1, 10, 9, 4, 2, 11, 'No', 28, 297), ('2032.0', 56, 'Male', 2, 'Technical Degree', 8, 12031.0, 1, 10, 9, 8, 4, 7, 'Yes', 6, 462), ('2056.0', 39, 'Female', 1, 'Marketing', 0, 15427.0, 1, 20, 9, 6, 2, 33, 'No', 15, 311), ('Unknown', 53, 'Female', 4, 'Life Sciences', 2, 4901.6, 0, 25, 3, 7, 3, 2, 'No', 41, 24), ('Unknown', 27, 'Male', 3, nan, 1, 4463.2, 0, 9, 1, 7, 0, 8, 'No', 18, 74), ('57.0', 30, 'Female', 2, nan, 1, 6942.2, 0, 12, 3, 7, 2, 1, 'No', 28, 624), ('Unknown', 35, 'Male', 5, 'Life Sciences', 1, 6162.0, 1, 9, 1, 8, 3, 18, 'No', 18, 176), ('78.0', 32, 'Male', 3, 'Medical', 1, 5126.0, 1, 9, 7, 8, 3, 1, 'No', 5, 162), ('104.0', 30, 'Male', 1, 'Life Sciences', 1, 9619.0, 2, 10, 3, 0, 1, 1, 'No', 28, 41), ('118.0', 46, 'Male', 2, 'Medical', 1, 7875.2, 0, 9, 4, 7, 3, 9, 'Yes', 17, 96), ('121.0', 30, 'Female', 2, nan, 1, 5010.0, 3, 11, 2, 7, 4, 4, 'No', 39, 130), ('125.0', 32, 'Male', 4, nan, 1, 6942.2, 0, 11, 5, 7, 0, 6, 'No', 39, 147), ('Unknown', 35, 'Male', 5, 'Marketing', 1, 7559.0, 2, 10, 0, 6, 3, 37, 'No', 18, 113), ('207.0', 32, 'Female', 3, 'Marketing', 1, 3469.8, 0, 9, 3, 7, 2, 8, 'No', 18, 165), ('227.0', 41, 'Male', 3, 'Life Sciences', 4, 19033.0, 1, 9, 1, 8, 2, 34, 'No', 31, 127), ('253.0', 40, 'Female', 1, 'Medical', 1, 18389.2, 1, 20, 9, 9, 2, 4, 'No', 52, 595), ('264.0', 45, 'Male', 2, nan, 9, 10400.0, 1, 20, 11, 8, 1, 2, 'No', 41, 19), ('291.0', 32, 'Male', 4, nan, 1, 6309.4, 0, 14, 9, 8, 2, 4, 'Yes', 18, 323), ('292.0', 30, 'Male', 1, 'Life Sciences', 1, 11390.4, 0, 11, 5, 8, 2, 1, 'No', 45, 156), ('306.0', 37, 'Male', 3, nan, 1, 2793.0, 3, 10, 0, 7, 1, 11, 'No', 54, 470), ('Unknown', 37, 'Male', 4, nan, 4, 4516.8, 1, 9, 5, 8, 2, 4, 'No', 10, 248), ('335.0', 40, 'Male', 2, 'Technical Degree', 1, 5674.0, 2, 9, 4, 7, 3, 24, 'No', 43, 76), ('Unknown', 36, 'Female', 4, nan, 7, 5538.0, 1, 9, 0, 8, 3, 24, 'No', 28, 146), ('420.0', 32, 'Male', 3, 'Life Sciences', 1, 9729.2, 1, 13, 4, 8, 3, 7, 'No', 39, 73), ('421.0', 38, 'Female', 2, 'Life Sciences', 3, 2951.6, 1, 10, 0, 1, 2, 25, 'No', 54, 348), ('441.0', 30, 'Female', 2, nan, 1, 19197.0, 2, 10, 1, 9, 2, 28, 'No', 43, 12), ('531.0', 39, 'Male', 1, nan, 1, 14593.0, 1, 21, 1, 6, 3, 1, 'No', 52, 97), ('549.0', 60, 'Female', 3, 'Life Sciences', 5, 8412.0, 0, 29, 11, 10, 5, 7, 'No', 52, 244), ('567.0', 30, 'Female', 4, 'Other', 0, 6268.8, 0, 9, 7, 8, 3, 22, 'No', 18, 28), ('581.0', 31, 'Male', 1, nan, 1, 3348.0, 1, 13, 0, 8, 6, 9, 'No', 45, 494), ('702.0', 33, 'Male', 3, 'Life Sciences', 1, 3578.2, 0, 10, 9, 7, 3, 3, 'Yes', 48, 430), ('716.0', 50, 'Male', 1, 'Medical', 1, 5309.0, 3, 20, 3, 8, 3, 28, 'No', 25, 539), ('772.0', 32, 'Male', 4, 'Life Sciences', 1, 6758.8, 2, 10, 4, 7, 2, 24, 'No', 11, 374), ('836.0', 42, 'Male', 3, nan, 1, 7654.0, 1, 9, 7, 8, 3, 29, 'No', 20, 35), ('840.0', 49, 'Female', 3, 'Marketing', 1, 12808.0, 2, 9, 7, 7, 3, 11, 'Yes', 17, 13), ('844.0', 27, 'Male', 1, nan, 1, 4978.8, 1, 9, 0, 8, 3, 5, 'No', 54, 617), ('Unknown', 33, 'Male', 3, 'Medical', 1, 16103.2, 1, 9, 0, 8, 5, 1, 'No', 39, 120), ('867.0', 52, 'Female', 4, nan, 3, 5830.8, 0, 9, 0, 0, 3, 26, 'No', 44, 532), ('889.0', 32, 'Male', 2, 'Life Sciences', 1, 6586.0, 1, 10, 5, 3, 3, 5, 'No', 39, 457), ('924.0', 36, 'Male', 1, 'Life Sciences', 0, 6760.2, 1, 16, 4, 11, 2, 14, 'No', 38, 229), ('Unknown', 31, 'Female', 2, nan, 1, 2519.0, 1, 9, 0, 0, 2, 20, 'No', 37, 60), ('Unknown', 36, 'Male', 4, 'Medical', 4, 17099.0, 0, 11, 3, 9, 6, 2, 'No', 25, 27), ('976.0', 52, 'Male', 2, 'Life Sciences', 2, 9718.6, 1, 9, 7, 8, 2, 1, 'No', 41, 362), ('992.0', 33, 'Male', 3, nan, 1, 4563.6, 0, 10, 6, 0, 2, 17, 'No', 41, 74), ('1002.0', 45, 'Male', 2, 'Life Sciences', 1, 6085.8, 1, 9, 0, 8, 2, 23, 'No', 28, 306), ('1073.0', 36, 'Female', 5, nan, 0, 13120.0, 0, 14, 7, 8, 2, 12, 'No', 45, 53), ('1138.0', 49, 'Male', 4, nan, 6, 6178.0, 1, 9, 2, 3, 3, 8, 'No', 15, 603), ('Unknown', 29, 'Female', 1, nan, 1, 3131.0, 1, 11, 3, 10, 3, 23, 'Yes', 18, 77), ('1192.0', 29, 'Female', 1, nan, 1, 5848.6, 1, 10, 0, 8, 5, 6, 'No', 25, 99), ('1196.0', 37, 'Female', 3, 'Life Sciences', 1, 8121.6, 1, 14, 3, 11, 2, 1, 'No', 5, 53), ('Unknown', 33, 'Male', 5, nan, 0, 4444.0, 2, 9, 0, 8, 3, 10, 'No', 18, 139), ('Unknown', 34, 'Female', 3, 'Medical', 4, 6674.0, 2, 11, 5, 10, 2, 19, 'No', 28, 613), ('1315.0', 28, 'Female', 3, nan, 0, 9852.0, 3, 9, 7, 5, 6, 1, 'No', 28, 351), ('1324.0', 31, 'Female', 4, nan, 1, 17861.0, 1, 10, 9, 6, 5, 2, 'No', 18, 486), ('1334.0', 42, 'Male', 1, 'Life Sciences', 0, 5291.0, 0, 20, 2, 10, 3, 2, 'No', 41, 272), ('1346.0', 40, 'Male', 3, 'Life Sciences', 1, 5579.4, 0, 9, 8, 8, 4, 2, 'No', 43, 114), ('1356.0', 34, 'Female', 2, 'Medical', 1, 15248.0, 0, 10, 9, 6, 6, 15, 'No', 39, 381), ('1423.0', 58, 'Female', 3, nan, 3, 7446.0, 1, 9, 1, 5, 3, 1, 'No', 53, 477), ('1459.0', 31, 'Female', 5, nan, 1, 13757.0, 0, 10, 4, 7, 2, 1, 'Yes', 7, 3), ('Unknown', 40, 'Male', 1, nan, 2, 16598.0, 1, 9, 4, 8, 5, 8, 'No', 54, 360), ('1472.0', 53, 'Male', 3, 'Medical', 4, 8759.4, 0, 9, 8, 8, 2, 2, 'No', 50, 452), ('1485.0', 34, 'Male', 3, nan, 7, 8901.8, 2, 14, 6, 9, 3, 15, 'No', 33, 299), ('Unknown', 35, 'Female', 3, 'Life Sciences', 1, 4285.0, 0, 11, 3, 3, 3, 16, 'No', 24, 100), ('1543.0', 37, 'Male', 3, nan, 1, 10124.0, 0, 10, 3, 7, 2, 13, 'No', 43, 76), ('1547.0', 42, 'Male', 3, nan, 2, 8482.6, 1, 20, 13, 9, 3, 2, 'No', 24, 102), ('1553.0', 45, 'Male', 4, nan, 1, 9714.0, 3, 10, 7, 7, 4, 1, 'No', 24, 187), ('1562.0', 30, 'Male', 3, nan, 1, 9924.0, 1, 10, 6, 7, 4, 1, 'Yes', 39, 5), ('1582.0', 38, 'Male', 3, 'Life Sciences', 0, 11245.0, 1, 9, 7, 7, 3, 14, 'No', 39, 522), ('1606.0', 50, 'Male', 5, 'Medical', 2, 3069.0, 1, 30, 12, 13, 3, 20, 'No', 23, 97), ('Unknown',

In [15]:
# INSERTAMOS LOS DATOS EN LA TABLA EMPLOYEE
cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()
query_insercion_employees = """INSERT INTO employees (
                                    EmployeeNumber, 
                                    Age, 
                                    Gender, 
                                    Education, 
                                    EducationField, 
                                    NumCompaniesWorked, 
                                    MonthlyIncome, 
                                    StockOptionLevel,
                                    YearsAtCompany, 
                                    YearsSinceLastPromotion,
                                    YearsWithCurrManager,
                                    TrainingTimesLastYear,                               
                                    DistanceFromHome, 
                                    Attrition,
                                    idWork,
                                    idSatisfaction) 
                                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""

try:
    mycursor.executemany(query_insercion_employees,valores_tabla_employee)
    cnx.commit()
    print(mycursor.rowcount, "registros insertados")
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

1486 registros insertados

In [16]:
# VALORES TABLA WORK_INFO

valores_tabla_work_info = list(set(zip(
    df_employees_completo['RemoteWork'].values,
    df_employees_completo['OverTime'].values, 
    df_employees_completo['BusinessTravel'].values,
    [int(x) for x in df_employees_completo['idWork'].values]
)))

print(valores_tabla_work_info)

[('Yes', 'Yes', 'Non-Travel', 17), ('No', 'No', 'travel_rarely', 38), ('Yes', 'No', 'travel_frequently', 20), ('No', 'No', 'Non-Travel', 6), ('Yes', 'No', 'travel_frequently', 29), ('No', 'No', 'Non-Travel', 15), ('No', 'No', 'travel_rarely', 47), ('Yes', 'No', 'travel_frequently', 38), ('No', 'Yes', 'travel_rarely', 40), ('No', 'Yes', 'travel_rarely', 49), ('Yes', 'Yes', 'Non-Travel', 53), ('No', 'No', 'travel_frequently', 53), ('Yes', 'No', 'travel_rarely', 18), ('Yes', 'No', 'travel_rarely', 45), ('Yes', 'No', 'non-travel', 18), ('Yes', 'No', 'travel_frequently', 6), ('Yes', 'No', 'travel_frequently', 15), ('No', 'No', 'travel_rarely', 33), ('Yes', 'Yes', 'Non-Travel', 12), ('Yes', 'No', 'Non-Travel', 53), ('Yes', 'Yes', 'Non-Travel', 21), ('Yes', 'No', 'travel_frequently', 24), ('Yes', 'No', 'travel_frequently', 33), ('No', 'No', 'non-travel', 24), ('Yes', 'Yes', 'Non-Travel', 39), ('No', 'Yes', 'travel_rarely', 44), ('No', 'No', 'travel_frequently', 39), ('No', 'Yes', 'travel_rarely', 53), ('No', 'No', 'travel_frequently', 48), ('Yes', 'No', 'travel_rarely', 13), ('Yes', 'No', 'travel_rarely', 22), ('Yes', 'No', 'travel_rarely', 31), ('Yes', 'No', 'non-travel', 4), ('Yes', 'No', 'travel_frequently', 1), ('No', 'No', 'travel_rarely', 19), ('Yes', 'No', 'Non-Travel', 39), ('Yes', 'Yes', 'Non-Travel', 7), ('No', 'No', 'travel_rarely', 28), ('Yes', 'No', 'travel_frequently', 10), ('Yes', 'No', 'Non-Travel', 48), ('Yes', 'No', 'travel_frequently', 19), ('No', 'No', 'travel_rarely', 37), ('No', 'Yes', 'travel_rarely', 21), ('Yes', 'Yes', 'Non-Travel', 25), ('No', 'No', 'travel_frequently', 25), ('No', 'Yes', 'travel_frequently', 9), ('No', 'Yes', 'travel_frequently', 18), ('No', 'Yes', 'travel_rarely', 39), ('No', 'No', 'travel_frequently', 43), ('No', 'No', 'non-travel', 37), ('No', 'No', 'travel_frequently', 52), ('Yes', 'No', 'travel_rarely', 8), ('Yes', 'No', 'travel_rarely', 17), ('Yes', 'No', 'travel_rarely', 26), ('Yes', 'No', 'Non-Travel', 34), ('No', 'No', 'travel_rarely', 23), ('Yes', 'No', 'Non-Travel', 43), ('No', 'No', 'non-travel', 5), ('Yes', 'No', 'Non-Travel', 52), ('Yes', 'Yes', 'Non-Travel', 20), ('No', 'No', 'travel_rarely', 41), ('No', 'No', 'travel_frequently', 20), ('No', 'Yes', 'travel_rarely', 25), ('No', 'No', 'travel_frequently', 38), ('No', 'Yes', 'travel_frequently', 31), ('Yes', 'Yes', 'non-travel', 24), ('Yes', 'No', 'travel_rarely', 12), ('Yes', 'No', 'travel_rarely', 21), ('Yes', 'No', 'Non-Travel', 20), ('No', 'No', 'travel_rarely', 9), ('Yes', 'No', 'Non-Travel', 29), ('No', 'No', 'travel_rarely', 18), ('Yes', 'No', 'Non-Travel', 38), ('Yes', 'Yes', 'Non-Travel', 6), ('No', 'No', 'travel_frequently', 6), ('Yes', 'No', 'Non-Travel', 47), ('No', 'Yes', 'travel_rarely', 20), ('No', 'No', 'non-travel', 18), ('No', 'Yes', 'Non-Travel', 46), ('Yes', 'Yes', 'travel_rarely', 28), ('Yes', 'Yes', 'travel_rarely', 37), ('Yes', 'Yes', 'travel_rarely', 46), ('Yes', 'Yes', 'non-travel', 28), ('Yes', 'No', 'travel_rarely', 7), ('Yes', 'Yes', 'non-travel', 37), ('Yes', 'No', 'Non-Travel', 15), ('Yes', 'No', 'Non-Travel', 24), ('Yes', 'No', 'Non-Travel', 33), ('Yes', 'Yes', 'Non-Travel', 1), ('No', 'No', 'travel_rarely', 22), ('No', 'Yes', 'travel_rarely', 6), ('No', 'No', 'travel_frequently', 10), ('No', 'No', 'non-travel', 4), ('Yes', 'No', 'Non-Travel', 51), ('No', 'No', 'Non-Travel', 48), ('No', 'Yes', 'Non-Travel', 41), ('Yes', 'Yes', 'travel_rarely', 23), ('No', 'No', 'travel_frequently', 28), ('Yes', 'Yes', 'travel_rarely', 41), ('Yes', 'No', 'Non-Travel', 10), ('No', 'No', 'travel_rarely', 8), ('Yes', 'No', 'Non-Travel', 28), ('No', 'Yes', 'travel_rarely', 1), ('Yes', 'No', 'Non-Travel', 37), ('No', 'No', 'Non-Travel', 43), ('Yes', 'Yes', 'travel_rarely', 9), ('Yes', 'Yes', 'travel_frequently', 25), ('No', 'No', 'Non-Travel', 52), ('Yes', 'Yes', 'travel_rarely', 18), ('No', 'No', 'travel_frequently', 23), ('Yes', 'Yes', 'non-travel', 18), ('Yes', 'No', 'Non-Travel', 5), ('No', 'No', 'travel_rarely', 3), ('Yes', 'No', 'Non-Travel', 23), ('No', 'No', 'Non-Travel', 29), ('No', 'No', 'Non-Travel', 38), ('No', 'Yes', 'Non-Travel', 22), ('No', 'No', 'Non-Travel', 47), ('No', 'Yes', 'Non-Travel', 31), ('Yes', 'Yes', 'travel_rarely', 31), ('Yes', 'No', 'Non-Travel', 9), ('Yes', 'No', 'Non-Travel', 18), ('No', 'No', 'Non-Travel', 24), ('Yes', 'Yes', 'travel_frequently', 6), ('No', 'No', 'Non-Travel', 33), ('Yes', 'Yes', 'travel_frequently', 15), ('No', 'No', 'Non-Travel', 42), ('Yes', 'Yes', 'travel_frequently', 24), ('Yes', 'No', 'travel_rarely', 54), ('Yes', 'No', 'non-travel', 45), ('Yes', 'No', 'non-travel', 54), ('No', 'No', 'Non-Travel', 10), ('No', 'No', 'Non-Travel', 28), ('Yes', 'Yes', 'travel_frequently', 10), ('Yes', 'Yes', 'Non-Travel', 48), ('No', 'No', 'Non-Travel', 37), ('Yes', 'Yes', 'travel_frequently', 28), ('Yes', 'Yes', 'travel_rarely', 12), ('Yes', 'No', 'travel_rarely', 49), ('Yes', 'No', 'non-travel', 31), ('No', 'No', 'Non-Travel', 5), ('Yes', 'No', 'travel_frequently', 28), ('Yes', 'No', 'travel_frequently', 37), ('No', 'Yes', 'Non-Travel', 7), ('No', 'No', 'Non-Travel', 23), ('Yes', 'Yes', 'Non-Travel', 43), ('No', 'Yes', 'travel_rarely', 48), ('Yes', 'Yes', 'Non-Travel', 52), ('No', 'No', 'Non-Travel', 41), ('Yes', 'Yes', 'travel_rarely', 7), ('No', 'Yes', 'Non-Travel', 25), ('No', 'Yes', 'non-travel', 39), ('No', 'Yes', 'travel_frequently', 54), ('Yes', 'No', 'travel_rarely', 53), ('Yes', 'Yes', 'Non-Travel', 29), ('No', 'No', 'travel_rarely', 50), ('No', 'No', 'Non-Travel', 18), ('Yes', 'No', 'travel_frequently', 41), ('Yes', 'Yes', 'Non-Travel', 38), ('No', 'Yes', 'travel_rarely', 43), ('No', 'No', 'non-travel', 41), ('Yes', 'No', 'travel_rarely', 39), ('Yes', 'No', 'travel_rarely', 48), ('Yes', 'No', 'non-travel', 21), ('Yes', 'No', 'non-travel', 39), ('Yes', 'No', 'non-travel', 48), ('Yes', 'No', 'travel_frequently', 18), ('Yes', 'Yes', 'Non-Travel', 24), ('Yes', 'No', 'travel_frequently', 27), ('No', 'No', 'travel_rarely', 54), ('Yes', 'No', 'travel_frequently', 45), ('No', 'Yes', 'non-travel', 20), ('No', 'Yes', 'travel_frequently', 35), ('Yes', 'No', 'travel_rarely', 16), ('Yes', 'No', 'travel_rarely', 25), ('Yes', 'No', 'travel_rarely', 34), ('Yes', 'No', 'travel_rarely', 43), ('Yes', 'No', 'travel_rarely', 52), ('Yes', 'No', 'non-travel', 25), ('Yes', 'No', 'travel_frequently', 4), ('Yes', 'Yes', 'Non-Travel', 10), ('No', 'No', 'travel_rarely', 31), ('Yes', 'Yes', 'Non-Travel', 19), ('No', 'Yes', 'travel_rarely', 24), ('No', 'No', 'Non-Travel', 8), ('Yes', 'No', 'travel_frequently', 31), ('Yes', 'Yes', 'Non-Travel', 28), ('No', 'Yes', 'travel_frequently', 48), ('Yes', 'No', 'travel_rarely', 11), ('Yes', 'No', 'travel_rarely', 20), ('Yes', 'No', 'travel_rarely', 29), ('Yes', 'No', 'travel_rarely', 38), ('Yes', 'No', 'non-travel', 20), ('Yes', 'No', 'travel_frequently', 8), ('No', 'Yes', 'travel_rarely', 10), ('Yes', 'Yes', 'Non-Travel', 14), ('No', 'No', 'travel_rarely', 35), ('No', 'No', 'non-travel', 8), ('Yes', 'Yes', 'Non-Travel', 23), ('No', 'No', 'travel_rarely', 53), ('No', 'Yes', 'travel_rarely', 37), ('No', 'No', 'non-travel', 26), ('No', 'Yes', 'travel_frequently', 25), ('Yes', 'Yes', 'travel_rarely', 54), ('No', 'Yes', 'travel_frequently', 52), ('Yes', 'No', 'travel_rarely', 6), ('Yes', 'No', 'travel_rarely', 15), ('Yes', 'No', 'travel_rarely', 24), ('Yes', 'No', 'travel_rarely', 33), ('Yes', 'No', 'non-travel', 15), ('No', 'No', 'travel_rarely', 12), ('Yes', 'No', 'Non-Travel', 32), ('Yes', 'No', 'travel_frequently', 3), ('No', 'No', 'travel_rarely', 21), ('Yes', 'No', 'Non-Travel', 41), ('Yes', 'No', 'travel_frequently', 12), ('Yes', 'No', 'Non-Travel', 50), ('Yes', 'Yes', 'Non-Travel', 18), ('No', 'No', 'travel_rarely', 39), ('No', 'No', 'travel_frequently', 18), ('No', 'No', 'non-travel', 12), ('No', 'No', 'travel_rarely', 48), ('No', 'Yes', 'non-travel', 23), ('No', 'No', 'non-travel', 39), ('Yes', 'No', 'travel_rarely', 1), ('Yes', 'No', 'travel_rarely', 10), ('Yes', 'No', 'travel_rarely', 19), ('Yes', 'No', 'non-travel', 10), ('No', 'No', 'travel_rarely', 7), ('No', 'No', 'travel_rarely', 16), ('Yes', 'No', 'Non-Travel', 36), ('Yes', 'No', 'travel_frequently', 7), ('No', 'No', 'travel_rarely', 25), ('No', 'Yes', 'travel_rarely', 9), ('Yes', 'No', 'Non-Travel', 45), ('No', 'Yes', 'travel_rarely', 18), ('Yes', 'No', 'Non-Travel', 54), ('No', 'No', 'travel_rarely', 43), ('No', 'No', 'travel_frequently', 22), ('No', 'Yes', 'travel_rarely', 27), ('No', 'No', 'travel_frequently', 31), ('No', 'No', 'non-travel', 25), ('No', 'Yes', 'Non-Travel', 53), ('Yes', 'No', 'travel_rarely', 5), ('Yes', 'No', 'Non-Travel', 13), ('Yes', 'No', 'Non-Travel', 22), ('Yes', 'No', 'Non-Travel', 31), ('No', 'No', 'travel_rarely', 20), ('Yes', 'No', 'Non-Travel', 40), ('Yes', 'Yes', 'Non-Travel', 8), ('Yes', 'No', 'Non-Travel', 49), ('No', 'Yes', 'Non-Travel', 39), ('Yes', 'Yes', 'travel_frequently', 37), ('No', 'No', 'travel_frequently', 26), ('No', 'No', 'non-travel', 20), ('No', 'Yes', 'travel_frequently', 10), ('No', 'Yes', 'Non-Travel', 48), ('Yes', 'Yes', 'travel_rarely', 30), ('Yes', 'Yes', 'travel_rarely', 39), ('Yes', 'Yes', 'travel_rarely', 48), ('Yes', 'Yes', 'non-travel', 39), ('Yes', 'No', 'Non-Travel', 8), ('Yes', 'No', 'Non-Travel', 17), ('No', 'No', 'travel_rarely', 6), ('Yes', 'No', 'Non-Travel', 26), ('No', 'No', 'travel_rarely', 15), ('Yes', 'No', 'Non-Travel', 35), ('No', 'No', 'travel_rarely', 24), ('No', 'No', 'Non-Travel', 50), ('No', 'No', 'travel_frequently', 21), ('No', 'Yes', 'Non-Travel', 43), ('Yes', 'Yes', 'travel_rarely', 25), ('No', 'Yes', 'Non-Travel', 52), ('Yes', 'Yes', 'travel_rarely', 43), ('Yes', 'No', 'Non-Travel', 12), ('No', 'No', 'travel_rarely', 1), ('Yes', 'No', 'Non-Travel', 21), ('No', 'No', 'travel_rarely', 10), ('No', 'Yes', 'Non-Travel', 20), ('No', 'No', 'travel_frequently', 7), ('No', 'No', 'Non-Travel', 36), ('No', 'Yes', 'Non-Travel', 29), ('No', 'No', 'travel_frequently', 16), ('No', 'No', 'Non-Travel', 54), ('Yes', 'Yes', 'travel_rarely', 20), ('No', 'Yes', 'Non-Travel', 38), ('Yes', 'Yes', 'travel_rarely', 38), ('Yes', 'Yes', 'non-travel', 20), ('Yes', 'No', 'Non-Travel', 7), ('Yes', 'No', 'Non-Travel', 16), ('Yes', 'No', 'Non-Travel', 25), ('No', 'No', 'Non-Travel', 22), ('No', 'Yes', 'Non-Travel', 6), ('No', 'No', 'Non-Travel', 31), ('No', 'No', 'travel_frequently', 2), ('No', 'Yes', 'Non-Travel', 24), ('No', 'No', 'travel_frequently', 11), ('Yes', 'Yes', 'travel_frequently', 22), ('No', 'No', 'Non-Travel', 40), ('Yes', 'Yes', 'travel_rarely', 6), ('No', 'No', 'Non-Travel', 49), ('Yes', 'No', 'Non-Travel', 11), ('No', 'No', 'Non-Travel', 17), ('No', 'Yes', 'Non-Travel', 10), ('No', 'No', 'Non-Travel', 44), ('Yes', 'Yes', 'travel_rarely', 10), ('No', 'Yes', 'Non-Travel', 28), ('No', 'No', 'Non-Travel', 53), ('No', 'Yes', 'Non-Travel', 37), ('Yes', 'Yes', 'travel_rarely', 19), ('Yes', 'No', 'travel_rarely', 47), ('Yes', 'No', 'non-travel', 38), ('Yes', 'No', 'Non-Travel', 6), ('No', 'No', 'Non-Travel', 3), ('No', 'No', 'Non-Travel', 12), ('Yes', 'Yes', 'Non-Travel', 41), ('Yes', 'Yes', 'travel_frequently', 12), ('Yes', 'Yes', 'Non-Travel', 50), ('No', 'No', 'Non-Travel', 39), ('Yes', 'Yes', 'travel_rarely', 5), ('Yes', 'Yes', 'travel_rarely', 14), ('No', 'No', 'non-travel', 53), ('No', 'No', 'Non-Travel', 7), ('Yes', 'No', 'travel_frequently', 39), ('No', 'No', 'Non-Travel', 25), ('Yes', 'No', 'travel_frequently', 48), ('No', 'No', 'Non-Travel', 34), ('No', 'Yes', 'Non-Travel', 18), ('Yes', 'Yes', 'Non-Travel', 54), ('No', 'No', 'non-travel', 48), ('No', 'Yes', 'non-travel', 41), ('Yes', 'No', 'travel_rarely', 28), ('Yes', 'No', 'travel_rarely', 37), ('Yes', 'No', 'non-travel', 28), ('Yes', 'No', 'non-travel', 37), ('Yes', 'No', 'travel_frequently', 25), ('No', 'No', 'Non-Travel', 11), ('Yes', 'Yes', 'Non-Travel', 31), ('No', 'No', 'travel_rarely', 52), ('No', 'No', 'Non-Travel', 20), ('No', 'Yes', 'Non-Travel', 4), ('Yes', 'No', 'travel_frequently', 43), ('Yes', 'No', 'travel_frequently', 52), ('No', 'No', 'non-travel', 52), ('No', 'Yes', 'non-travel', 54), ('Yes', 'No', 'non-travel', 5), ('Yes', 'No', 'travel_rarely', 41), ('Yes', 'No', 'travel_rarely', 50), ('Yes', 'No', 'non-travel', 41)]

In [17]:
# INSERCION DATOS EN LA TABLA WORK_INFO

# INSERTAMOS LOS DATOS EN LA TABLA EMPLOYEE
cnx = mysql.connector.connect(user = 'root',password = 'AlumnaAdalab',host = "127.0.0.1",database = 'Proyecto')

mycursor = cnx.cursor()
query_insercion_work_info = """INSERT INTO work_info (
                                RemoteWork,
                                OverTime,
                                BusinessTravel,
                                idWork)
                                VALUES (%s, %s, %s, %s)"""

try:
    mycursor.executemany(query_insercion_work_info,valores_tabla_work_info)
    cnx.commit()
    print(mycursor.rowcount, "registros insertados")
    
except mysql.connector.Error as err:
    print(err)
    print(f"Error Code {err.errno}")
    print(f"SQLSTATE {err.sqlstate}")
    print(f"MESSAGE {err.msg}")

cnx.close()

349 registros insertados